src/MapControls.tsx, src/index.ts
The title says it all, I added MapControls:
```js
// import
import { MapControls } from "drei"
// and use
<MapControls />
```
=> add map controls

package.json, src/TransformControls.tsx, yarn.lock
=> Use lodash pick/omit to fix #29

README.md
@drcmda how does this wording look?  It's as succinct as I could manage, but it's still longer than the comments on the other props...
Resolves react-spring/drei#52
=> Amend doco of HTML scaleFactor prop to mention PerspectiveCamera.

README.md, src/Stats.tsx
=> Lets Stats be mounted in a custom DOM element

src/PositionalAudio.tsx
Updated PositionalAudio types to correctly mark distance and loop as optional as they have defaults
=> Update PositionalAudio prop typing

src/index.tsx
Seems that DeviceOrientationControls is missing and it makes it more complex to use
=> added DeviceOrientationControls to index

.storybook/stories/Line.stories.js, README.md, src/Line.tsx
=> Renamed linewidth to lineWidth

package.json, yarn.lock
to apply change here: https://github.com/protectwise/troika/commit/4d4bfbc5d4d730eb0098d33beb1c3c562037fddf
=> bump troika-three-text version

.storybook/stories/useProgress.stories.js
issue: https://github.com/pmndrs/drei/issues/119
=> Issue #119: Add useProgress story

src/Sky.tsx
An attempt at fixing types in Sky. I used the types in `Stars` as a basis for this change.
=> Fix types in Sky

src/Loader.tsx
I suggest adding [csstype](https://www.npmjs.com/package/csstype) to have proper types for the styles, thoughts?
=> Add Loader properties types

src/OrthographicCamera.tsx, src/PerspectiveCamera.tsx
Makes children and makeDefault optional
=> Fixes types for ortho & perspective cameras

.storybook/stories/Text.stories.js
=> Issue #127: Add a custom material story for Text

.github/workflows/release.yml, src/core/useFBO.tsx
@AndrewPrifer it's all your bb
=> Ts use fbo

.storybook/stories/Reflector.stories.tsx, README.md, src/core/Reflector.tsx, src/materials/ReflectorMaterial.tsx
Adds the depth buffer to the reflector component
=> Reflector with depth texture

package.json, yarn.lock
Update troika-text to the newest version.
=> fix: updates troika-three-text to 0.38.1

src/core/useProgress.tsx
Related to https://github.com/pmndrs/drei/pull/280#issuecomment-771319948
=> feat: Create a new instance for each new useProgress instance

.storybook/index.css, .storybook/stories/HTML.stories.tsx, README.md, src/web/Html.tsx
Resolves https://github.com/pmndrs/drei/issues/295
Optionally override html calculate position via prop
=> Pass custom html function

src/web/Html.tsx
More safety checks that we need to make unmounting a peaceful process.
=> fix: make Html component HMR-proof

src/core/Reflector.tsx
`args` prop could only have two items, but in actuality it should match `planeBufferGeometry.args`. 
edited the type for ReflectorProps & also added `forwardRef` to the component.
=> fix: args is passed to planeBufferGeometry & add forwardRef

.storybook/stories/Line.stories.tsx, .storybook/stories/MapControls.stories.tsx, .storybook/stories/Shapes.Parametric.stories.tsx, .storybook/stories/TransformControls.stories.tsx, .storybook/stories/useAnimations.stories.tsx, .storybook/stories/useEdgeSplit.stories.tsx, .storybook/stories/useHelper.stories.tsx, README.md, package.json, src/core/CameraShake.tsx, src/core/ContactShadows.tsx, src/core/CurveModifier.tsx, src/core/DeviceOrientationControls.tsx, src/core/Effects.tsx, src/core/Environment.tsx, src/core/FlyControls.tsx, src/core/Line.tsx, src/core/MapControls.tsx, src/core/OrbitControls.tsx, src/core/PointerLockControls.tsx, src/core/Sky.tsx, src/core/TrackballControls.tsx, src/core/TransformControls.tsx, src/core/useEdgeSplit.tsx, src/core/useFBX.tsx, src/core/useGLTF.tsx, src/core/useSimplification.tsx, src/core/useTessellation.tsx, yarn.lock
- Flat three-stdlib imports and bump version
- Fix FBX loader (three-stdlib)
- Fix MapControls (three-stdlib)
- [ x ] Documentation updated
- [ x ] Storybook entry updated
=> Three stdlib

package.json, rollup.config.js, yarn.lock
resolves #329 
We weren't capturing .tsx files for`cjs` exports, only `.ts` files. This has now changed & we also use `tersrer` to minify the `cjs` code.
=> [fix] Capture .tsx files & add terser

README.md
Had a little performance regression after copying these props from documentation and eventually traced it to `mixBlur`. Figured I'd add a word of warning to future copy-pasta'ers.
=> docs: Add mixBlur disclaimer

package.json, src/core/useGLTF.tsx, yarn.lock
Fix ssr by doing flat import in useGLTF
=> fix: ssr issue because no flat import meshopt

README.md, src/core/Center.tsx, src/core/Stage.tsx
=> feature: Adds Stage prototyping component

.storybook/stories/Text.stories.tsx, package.json, src/core/Text.tsx
resolves #371 ... I updated [troika-three-text](https://github.com/protectwise/troika/tree/master/packages/troika-three-text) to it's latest version which now comes with bidi and "direction" support.
... see above.
=>  updated troika-three-text dependency for bidi and ltr support

.storybook/readme.md
`npm install` errors
Project moved to yarn, updating installation instructions
=> fix: Update readme.md

README.md
Please don't remove that feature, it is very useful 🙏
=> Remove "might be removed" note

src/core/TrackballControls.tsx
I was attempting to use TrackballControls in a project and noticed that it was not remounting consistently with fast refresh. After comparing them to OrbitControls, I realized that the implementations had fallen out of sync quite a bit. This PR converts the implementation style of TrackballControls to better match OrbitControls.
https://github.com/pmndrs/drei/blob/master/src/core/OrbitControls.tsx
There are still some minor differences:
- TrackballControls doesn't support dampening
- TrackballControls uses the constructor to connect to the `gl.domElement` rather than in the `useEffect`.
=> fix: update TrackballControl to better match OrbitControls

src/core/OrbitControls.tsx
Hopefully fixes #467 (was not able to use forked repo as package.json dependency in the referenced codesandbox https://codesandbox.io/s/dreiorbitcontrolsenablerotate-c2j9i?file=/src/index.js:392-430) 🤞
=> fix: re-enable controls.connect in OrbitControls

src/core/useGLTF.tsx
=> fix: useGLTF typing

README.md
Add Billboard storybook link to readme
=> chore(docs): Add Billboard storybook link to readme

.storybook/stories/FirstPersonControls.stories.tsx, README.md, src/core/FirstPersonControls.tsx, src/core/index.ts
Working on a project that needed first person controls and found that y'all are missing the wrapper for it.
Added a wrapper for three.js [FirstPersonControls](https://threejs.org/docs/#examples/en/controls/FirstPersonControls)
One of my first contributions to anything on github so so let me know if I've done anything wrong!
=> feat: add FirstPersonControls component

README.md, src/core/GizmoHelper.tsx
resolves https://github.com/pmndrs/drei/issues/519
add `renderPriority` option to GizmoHelper
=> fix: add renderPriority option to GizmoHelper

src/web/ScrollControls.tsx
I tried to create a PR for TransformControls and pre-commit hook fails on a file that I didn't change.
A file (`web/scroll`) has been committed although it shouldn't have passed the linting stage.
=> fix: remove white space added in #653

package.json
resolves #645
The file operations should be case sensitive.
=> chore(docs): change readme to README

README.md
if someone is copy pasting the code from here, this would make their lives a bit easier
the example is doing {...props} but no props are passed to the object
=> Update Scroll example on README

README.md
Storybook links in the README were broken.
I've changed broken storybook links with the right ones.
=> fix: README broken storybook links

.storybook/stories/TransformControls.stories.tsx, src/core/TransformControls.tsx
Fixes https://github.com/pmndrs/drei/issues/746
=> fix: added missing cleanup to TransformControls #746

.storybook/stories/ArcballControls.stories.tsx, .storybook/stories/CurveModifier.stories.tsx, .storybook/stories/Reflector.stories.tsx, .storybook/stories/TransformControls.stories.tsx, .storybook/tsconfig.json, README.md, package.json, src/core/ArcballControls.tsx, src/core/ContactShadows.tsx, src/core/CubeCamera.tsx, src/core/CurveModifier.tsx, src/core/Environment.tsx, src/core/GradientTexture.tsx, src/core/MeshReflectorMaterial.tsx, src/core/OrbitControls.tsx, src/core/Reflector.tsx, src/core/RoundedBox.tsx, src/core/Stats.tsx, src/core/TransformControls.tsx, src/helpers/Position.tsx, src/materials/MeshReflectorMaterial.tsx, src/web/Select.tsx, yarn.lock
Merges some upstream fixes from master with beta.
=> [beta] fix: sync with master, r137 fixes

package.json, yarn.lock
[Bump Troika for performance improvements](https://github.com/protectwise/troika/commit/7e871f77c17dbbb68ca5c2240f569d4b102031f0)
=> feat: bump troika text 0.45.0

README.md
Add note about usage of `preset` prop is production environments.
=> Docs: Add <Environment> preset clarification

README.md
Fixed minor typos.
To make `README.md` more readable.
Fixed minor typos.
=> Fix typos in `Center` section of `README.md`

README.md
Fixed spelling, clarified language, and removed empty hash-link.
Just to make the documentation a little more readable.
I fixed a couple typos, improved readability, and deleted empty hash link.
=> Fix typos in `AdaptiveDpr` section of `README.md`

package.json, yarn.lock
bump troika to use gpu-accelerated sdf generator
=> feat: bump troika to use gpu-accelerated sdf generator

package.json, yarn.lock
=> fix: updates meshline

README.md
=> docs: adds missing props for `trail` to readme

src/core/Trail.tsx
=> fix: `Trail` with no children

.storybook/stories/Trail.stories.tsx, src/core/Float.tsx, src/core/Trail.tsx
=> Fix: Trail performance; Trail on Float;

src/core/GizmoViewcube.tsx
- Closes #791
- relate to https://github.com/pmndrs/react-three-fiber/pull/2145
FYI: [discussion](https://github.com/pmndrs/react-three-fiber/issues/1912#issuecomment-1076981253)
=> fix(GizmoViewcube): adapt to R3F new `attach` API

.storybook/stories/Sampler.stories.tsx, README.md, src/core/ComputedAttribute.tsx, src/core/Sampler.tsx, src/core/index.ts
<details>
<summary>Details</summary>
🐵   https://codesandbox.io/s/wn3cmj
🟢  https://codesandbox.io/s/r3f-fairly-realistic-grass-ehflx3
</details>
=> feat: adds Sampler & ComputedAttribute

README.md, src/core/ContactShadows.tsx
Requested
`color` prop to Contact Shadows.
Also updates readme for Cloud's `color` and `depthTest` prop
=> Feat: Add color to Contact Shadows

src/core/PointMaterial.tsx
Add type for `PointMaterial`
- Close #773
=> fix: `PointMaterial` type

.storybook/stories/Environment.stories.tsx, src/core/Environment.tsx
This PR resolves https://github.com/pmndrs/drei/issues/809.
Set correct mapping for the texture.
```javascript
texture.mapping = isCubeMap ? CubeReflectionMapping : EquirectangularReflectionMapping
```
=> fix(Environment): cubeMap mapping

package.json, src/core/useCamera.tsx, yarn.lock
Uses state.pointer instead of state.mouse. Also updates three-stdlib to broaden supported three versions.
=> fix(useCamera): use pointer, bump stdilb

README.md, src/core/Stars.tsx
`Stars` component can't control the speed of `star` twinkle
- Close #852
Add a `speed` props
=> feat: add `speed` for `Stars`

.storybook/stories/Environment.stories.tsx, README.md, src/core/Environment.tsx, src/helpers/glsl/GroundProjection.frag.glsl, src/helpers/glsl/GroundProjection.vert.glsl
Because car configurators needed to be easier to make 
Ground proection for `Environment` component. 
```jsx
<Environment ground />
<Environment ground={{ height, radius }} />
```
=> feat: Ground projection for Env maps

src/core/Environment.tsx
=> fix(Environment): Make width dynamic; Expose `useEnvironment`

.storybook/stories/CurveModifier.stories.tsx
[CurveModifier](https://drei.pmnd.rs/?path=/story/modifiers-curvemodifier--curve-modifier-st) doesn't show text
=> docs: `CurveModifier` storybook

.storybook/stories/Trail.stories.tsx
Change the `Trail` story name to be more genaric. Related to https://github.com/pmndrs/drei/issues/821
Change the name from `Trail on Float components` to `Trail with Ref target`.
=> docs: change trail story name to be more generic

package.json, yarn.lock
- https://github.com/pmndrs/three-stdlib/pull/151
Upgrade `three-stdlib`
=> fix: updates `three-stdlib` to type problem with `Line` component

README.md, src/core/useMatcapTexture.tsx, src/core/useNormalTexture.tsx, src/core/useTexture.tsx
=> fix: Add onLoad callback to useTexture, and other texture hooks.

src/core/Bounds.tsx, src/core/shapes.tsx
This adds CapsuleBufferGeometry to shapes. I also snuck in an ESLint fix.
=> feat: add CapsuleBufferGeometry to shapes

.storybook/stories/TransformControls.stories.tsx, package.json, yarn.lock
=> feat: Bump stdlib; Add `reset` to transfromControls story

src/core/MapControls.tsx
add makeDefault prop to MapControls (like OrbitControls) to be able to disabled MapControls while using a TransformControls
=> feat: add makeDefault prop to MapControls

.storybook/stories/Text3D.stories.tsx, src/core/Text3D.tsx
=> Add `bevelSegments` to Text3D

README.md
=> docs: typo in README: "scencil" to "stencil"

.storybook/stories/Text.stories.tsx
There's a typo in `Text.stories.tsx` file where the a component meant to show RTL support for Text, it was mistakenly named `TextLtrScene` instead of `TextRtlScene`
Just renamed it as `TextRtlScene` and also changed the story name to be `Text Rtl`.
=> Fixed a typo

src/core/RenderTexture.tsx
=> feat: Add `samples` prop to `RenderTexture`

.storybook/stories/Sampler.stories.tsx, README.md, src/core/Sampler.tsx
Adds `useSurfaceSampler` as it is sometimes useful to have sampler result as a buffer.
=> feat: Add `useSurfaceSampler` hook

src/core/pivotControls/AxisArrow.tsx, src/core/pivotControls/AxisRotator.tsx, src/core/pivotControls/PlaneSlider.tsx, src/core/pivotControls/context.ts, src/core/pivotControls/index.tsx
There already are limits for rotation; Translation limits might be useful somewhere as well
This PR includes translation limits and some other related fixes: translation value display and the displayValues flag for enabling / disabling the caption.
=> feat: translation limits

src/core/Points.tsx
=> fix #1067 (unwanted log)

README.md
A couple small changes make the readme easier for me to read 
Tried to use an example from the readme, found the missing slash in a `TransformControl` example made it broken. Was also briefly confused about a spelling mistake in HTML
=> Couple spelling and syntax errors

package.json, yarn.lock
Follow-up to https://github.com/pmndrs/three-stdlib/pull/195, https://github.com/mrdoob/three.js/issues/24799.
=> chore(deps): upgrade stdlib

README.md
I corrected the spelling of `aspect ratio`.
I changed the word from `ration` to `ratio`.
=> docs: correct spelling of ratio

.storybook/stories/Stats.stories.tsx
The `Stats` story doesn't work do to a typo.
Fix the typo and remove the unnecessary type definition.
=> fix: stats story

.storybook/stories/Trail.stories.tsx, src/core/Trail.tsx
Fixes #1109
Portals the Trail directly into the scene causing it to effectively ignore parent trasnforms
=> fix: Trail position when inside transformed parent;

src/core/useHelper.tsx
Helper is never disposed
Dispose helper on destroy
=> useHelper - dispose helper

README.md
- Address confusion around how the shape components can be used
- see: https://github.com/pmndrs/drei/issues/1195
- Created a separate section for the mesh+geometry shortcut components, improved text and examples
- Added prop breakdown to `RoundedBox` section
=> docs: improve mesh+geometry shortcut components section, RoundedBox section

.storybook/stories/HTML.stories.tsx, README.md, src/web/Html.tsx
Prevents large breakign chnage to existing projects. Can probably revert in next Major
=> fix: make HTML default to legacy occlusion

src/web/Html.tsx
=> fix: html occlude always on

src/web/KeyboardControls.tsx
Fixes the `@deprecated — Please use subscribeWithSelector middleware` deprecation warning which is a false positive since we're just using vanilla types.
=> fix(KeyboardControls): don't use deprecated Zustand types

src/materials/DiscardMaterial.tsx
Fixes #1236. The FS in DiscardMaterial just needed its output set to anything before discarding.
=> fix: `GL_INVALID_OPERATION` on AccumulativeShadows

src/web/Html.tsx
Fixes #1228 by making the canvas always under the `<Html />` parents.
=> fix: `<Html />` race conditions canvas z-index

.storybook/stories/Spotlight.stories.tsx, README.md
Fixes weird error in storybook. Related to suspense
=> fix: Spotlight/Shadows story

yarn.lock
`yarn upgrade camera-controls` to latest v2.2.1
=> chore(CC): upgrade camera-controls

src/core/softShadows.tsx
=> fix: set return type to null as a fn w/ return type 'void' is not a valid JSX element

README.md
Fixes a spelling mistake in README.md
Fixes a spelling mistake in README.md
=> fix: spelling mistake in README.md

README.md
fixes some minor spelling mistakes.
=> Fixes Typos in Readme

package.json, yarn.lock
=> fix(deps): pin react-spring

README.md
The example was causing the error.
=> docs: fix syntax

README.md
Update doc for `makeDefault`/`controls` state
=> `controls` root state example

.storybook/stories/KeyboardControls.stories.tsx, README.md
For WASD keys use `KeyboardEvent.code` instead of `KeyboardEvent.key` which requires duplicating them for lower- and uppercase and works only when EN language is selected on user's device.
=> KeyboardControls example: case & language independent WASD keys

README.md
TransformControls link was broken
Update link to this story
=> fix: readme storybook link for TransformControls

src/core/useHelper.tsx
Ensures that helpers are correctly added to the scene in a timely fashion.
=> fix(useHelper): init helper on layout

.storybook/stories/useVideoTexture.stories.tsx, README.md
Adding a simple story for `useVideoTexture`
=> chore(useVideoTexture): adding a story

README.md
More doc for `useVideoTexture` with mediaStream
=> docs(useVideoTexture): documenting with mediaStream

src/web/View.tsx
Reinforce View component by adding a check to see if the reference is defined.
Related:
https://github.com/pmndrs/react-three-next/pull/117
#1376
=> fix: add if defined check on rect reference

.storybook/stories/Wireframe.stories.tsx, src/core/Wireframe.tsx, src/materials/WireframeMaterial.tsx
- Disallows WireframeGeometry as input
- Scopes helper functions to avoid conflicts
- add cleanup to effects
=> fix: Bug with `<Wireframe />`

README.md
There is a typo in the README.
I've fixed said typo.
=> Fixed typo of 'propeties' → 'properties'

src/core/Example.tsx
Dealing with a async font loading issue
=> fix(Example): adding Suspense to wait font to be loaded

src/core/MarchingCubes.tsx
- Fix MarchingCubes component
- A recent change in `three-stdlib` renamed the `MarchingCubes` `onBeforeRender` method to `update`
- https://github.com/pmndrs/three-stdlib/commit/858d35dd6cfaf4a5ed78dadd84ea8448b692ac3f#diff-d40153ab1d5283c36999198869797c74daac6b9f70020a0e3d7dc1238d70b4a5
- The `onBeforeRender` method was called by three.js, but `update` isn't
- Updated the MarchingCubes component to call `update` in `useFrame`
=> fix(MarchingCubes): missing update

README.md
- FaceControls events
- FaceControls `manualDetect` prop
- FaceControls `manualUpdate` prop
=> docs(FaceControls): events + manualDetect/Update methods

src/core/CameraControls.tsx
Though I'm not sure it'll make a practical difference immediately, this change makes it so the threejs imports are explicit to allow for easier/better tree-shaking
=> feat: improve tree-shake-ability of CameraControls

README.md, src/core/GradientTexture.tsx
To support radial gradient as a texture
Added support for Radial Gradient texture. Extended the GradientTexture to include the radial gradient variation.
Added information on ReadMe
- [ x] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
=> feat: extended gradient texture with radial variation

src/core/useProgress.tsx, src/web/KeyboardControls.tsx, src/web/Select.tsx
See https://github.com/pmndrs/drei/pull/1550#issuecomment-1614800208
=> fix: fallback Zustand for ESM

package.json, src/core/FaceLandmarker.tsx, yarn.lock
https://www.npmjs.com/package/@mediapipe/tasks-vision/v/0.10.2 is out => upgrading
=> mediapipe 0.10.2

src/core/DeviceOrientationControls.tsx, src/core/PointerLockControls.tsx
=> fix(controls): support reactive camera

package.json, yarn.lock
Upgrading the version of three-stdlib. Would love to get a release that fixes the error for me in this [issue](https://github.com/pmndrs/three-stdlib/pull/284).
=> chore: update three stdlib

README.md
=> Added a closing slash to PerformanceMonitor example and also a typo on const declaration from "set" to "setDpr"

README.md, src/core/RoundedBox.tsx
RoundedBox didn't support the option to programmatically remove the bevel. There is merit in having the RoundedBox work as a rounded corner plane geometry
Added a parameter to allow the removal of bevel segments (setting them to `0`)
- [x ] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
- [x ] Ready to be merged
=> feat(RoundedBox): Add bevel as optional

src/core/MeshTransmissionMaterial.tsx
=> fix(MeshTransmissionMaterial): set anisotropy for bad chunks

src/core/useTexture.tsx
=> fix(useTexture): support experimental universal backend

package.json, rollup.config.js, src/core/AccumulativeShadows.tsx, src/core/Caustics.tsx, src/core/Facemesh.tsx, src/core/Grid.tsx, src/core/Image.tsx, src/core/Instances.tsx, src/core/MeshPortalMaterial.tsx, src/core/Outlines.tsx, src/core/PointMaterial.tsx, src/core/Points.tsx, src/core/Sparkles.tsx, src/core/SpriteAnimator.tsx, src/core/Stars.tsx, src/helpers/constants.ts, src/materials/ConvolutionMaterial.tsx, src/materials/MeshRefractionMaterial.tsx, src/materials/SpotLightMaterial.tsx, src/web/KeyboardControls.tsx, src/web/useCursor.tsx, yarn.lock
Mirrors https://github.com/pmndrs/three-stdlib/pull/292.
=> fix: tree-shake module side-effects

package.json, yarn.lock
=> fix: update three-mesh-bvh for ANGLE

.storybook/stories/Shadow.stories.tsx, src/core/Shadow.tsx
To fix this kind of type issues
=> fix(Shadow): better types

src/core/FaceControls.tsx, src/core/FaceLandmarker.tsx
=> fix: lazy import mediapipe

src/web/Html.tsx
Fixes #1723
Reverts pmndrs/drei#1695
=> fix: revert "fix(Html): use transform for perspective browser issues"

src/materials/SpotLightMaterial.tsx
Fixes #1722. Related: https://github.com/mrdoob/three.js/issues/23072.
=> fix(SpotLight): support for logarithmic depth

src/core/MotionPathControls.tsx
Update <MotionPathControls> type to allow children.
=> fix(MotionPathControls): update type

README.md, src/core/Bounds.tsx
Because of a recent Bounds component change, README.md had to be updated
Updated README.md
Also included minor type changes and an additional reset() call before fit in effect (should fix a possible issue with fit property if the camera is orthographic).
=> Docs: Bounds docs update

README.md
Typo in useCursor hook's docs
Fixed typo
=> fix: README typo in useCursor hook docs

package.json, src/core/Text.tsx
Allows `<Text />` to be bold and/or italic. Fixes #1830.
Adds the `fontWeight` and `fontStyle` from troika-three-text (bumped to latest version for this) properties onto `<Text />`.
(Looks like not all properties were documented separately from the TypeScript definitions before either, so I don't think it makes sense to add that in this PR.)
=> feat(Text): support fontWeight and fontStyle

src/core/Text.tsx
Fixes #1840 by working around a recurring Next/SSR bundler issue.
=> fix(Text): lazy import Troika

src/web/DragControls.tsx
=> fix(DragControls): null check controls

src/web/DragControls.tsx
Allow configure drag gesture config
Drag config of use-gesture
=> Drag controls drag config

.storybook/stories/Helper.stories.tsx, README.md, src/core/Helper.tsx, src/core/index.ts
Provide a declarative alternative to the `useHelper` hook
Added a component `<Helper />` that lets you add helpers declaratively
Example using `<Helper />`:
```ts
const Scene: React.FC<StoryProps> = ({ showHelper }) => {
return (
<Sphere>
<meshBasicMaterial />
<Helper type={BoxHelper} args={['royalblue']} />
<Helper type={VertexNormalsHelper} args={[1, 0xff0000]} />
</Sphere>
)
}
```
Example using `useHelper`:
``` ts
const Scene: React.FC<StoryProps> = ({ showHelper }) => {
const mesh = React.useRef()
useHelper(mesh, BoxHelper, 'royalblue')
useHelper(mesh, VertexNormalsHelper, 1, 0xff0000)
return (
<Sphere ref={mesh}>
<meshBasicMaterial />
</Sphere>
)
}
```
=> feat: add Helper component, declarative alternative to useHelper

.storybook/public/suzanne-high-poly.gltf, src/web/useCursor.tsx
Just a small suggestion. 💙
This change does not affect the functionality of the code, and has been updated to ensure consistency in code style.
I ran Prettier and modified codes that violated formatting rules.
=> chore: realign code with Prettier

src/core/useFont.tsx
Hello, we separated concerns inside the useFont loader function logic and refactored it to improve readability.
Separated concerns within the loader function for improved clarity and maintainability. Specifically, divided the font loading logic into two distinct functions: `loadFontData` for fetching the font data asynchronously, and `parseFontData` for parsing the loaded font data.
=> fix: splitting things mixed in the useFont loader function logic

src/core/Text.tsx
Fixes #1886 (unconfirmed). Reverts #1841 as #1840 is a downstream issue.
=> fix(Text): don't lazy load troika

.storybook/main.ts, .storybook/stories/Example.stories.tsx, .storybook/stories/Facemesh.stories.tsx, .storybook/stories/Float.stories.tsx, .storybook/stories/Line.stories.tsx, .storybook/stories/MeshDistortMaterial.stories.tsx, .storybook/stories/MeshWobbleMaterial.stories.tsx, .storybook/stories/Outlines.stories.tsx, .storybook/stories/Resize.stories.tsx, .storybook/stories/Segments.stories.tsx, .storybook/stories/Shapes.RoundedBox.stories.tsx, .storybook/stories/Sky.stories.tsx, .storybook/stories/Spotlight.stories.tsx, .storybook/stories/Stage.stories.tsx, .storybook/stories/Text.stories.tsx, .storybook/stories/Text3D.stories.tsx, .storybook/stories/TransformControls.stories.tsx, .storybook/stories/Wireframe.stories.tsx, .storybook/stories/shaderMaterial.stories.tsx, .storybook/stories/useAnimations.stories.tsx, .storybook/stories/useBVH.stories.tsx, .storybook/stories/useContextBridge.stories.tsx, .storybook/stories/useMatcapTexture.stories.tsx, .storybook/stories/useNormalTexture.stories.tsx, .storybook/stories/useProgress.stories.tsx, .storybook/stories/useTrailTexture.stories.tsx, package.json, yarn.lock
knobs are deprecated, and not supported anymore in sb8
removing any knob
=> chore: rm knobs

README.md
=> docs: toc update

.github/workflows/release.yml
=> actions bumps

src/core/Texture.tsx
remove console pollution by removing debug logs
removed `console.log()`
=> fix(Texture): remove console.log

.github/workflows/release.yml
=> chore: fix try 01

src/core/Line.tsx
lineMaterial is not disposed in the Line component.
Dispose of lineMaterial in Line component.
=> fix: dispose line material

src/core/Gltf.tsx
I created a ticket with an explanation:
fixes [Issue #2118](https://github.com/pmndrs/drei/issues/2118)
Solution explanation in the ticket ([Issue #2118](https://github.com/pmndrs/drei/issues/2118)) too 
- [x ] Ready to be merged
=> fix: gltf preload types update, make useDraco and useMeshopt optional

src/core/VideoTexture.tsx
https://discord.com/channels/740090768164651008/741751532592038022/1294603200455774271
=> `VideoTexture` - dispose()

.storybook/stories/VideoTexture.stories.tsx, docs/loaders/video-texture-use-video-texture.mdx, package.json, src/core/VideoTexture.tsx, yarn.lock
=> `useVideoTexture` enhancements

.storybook/stories/VideoTexture.stories.tsx, docs/loaders/video-texture-use-video-texture.mdx, src/core/VideoTexture.tsx
=> fix(useVideoTexture): playsInline for ios

.gitignore
yarn files weren't properly ignore
properly ignore yarn files
=> chore: Update .gitignore to include necessary files and directories

.husky/pre-commit
=> chore: typecheck on pre-commit

docs/loaders/video-texture-use-video-texture.mdx, src/core/VideoTexture.tsx
Adding a `useVideoTexture`/`VideoTexture` `onVideoFrame` [rVFC](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestVideoFrameCallback) callback option
=> `useVideoTexture` rVFC

package.json, test/e2e/e2e.sh, yarn.lock
=> e2e react19 fix

src/web/FaceControls.tsx
=> `FaceControls[facemesh]` overridable children

test/e2e/e2e.sh
Pins the create vite workflow since 6.1.1+ includes a breaking change https://github.com/vitejs/vite/pull/18917.
=> chore(CI): pin create vite workflow

docs/shaders/mesh-reflector-material.mdx
Debug uniform was removed with cc972ae6e07ec115113b26cef314d491bd636eb9
=> docs: update mesh-reflector-material.mdx

docs/controls/camera-controls.mdx
=> docs: CameraControls[camera]

docs/misc/fbo-use-fbo.mdx, src/core/Fbo.tsx
=> fix: Fbo types

package.json, yarn.lock
Update camera-controls to @latest (ie: 3.1.0)
=> feat: up camera-controls@latest
