src/HTML.tsx

In some cases when you have more than one children it may give the following error:
FIX: Removes the children prop, since it is already found in React.HTMLAttributes<HTMLDivElement>

Fixed children typing in HTML

---

src/TransformControls.tsx

Fixes #21.
When used, only set transforms on `<TransformControls/>` but not in the wrapped object, e.g.
```jsx
<TransformControls position={props.position}>
<mesh>
{/* geometry and material omitted for brevity */}
</mesh>
</TransformControls>
```

Forward transforms to wrapped group

---

src/shapes.tsx

Shapes don't work atm, since the lowercase b makes the name "boxbufferGeometry" instead of the correct camel name

Fixes error in shapes

---

README.md
src/Stars.tsx

This PR introduces Stars component, which adds blinking shader-based starfield to the scene. Caveats:
* In order to maintain z-buffer sorting for proper blending, the distribution within `[radius, radius + depth]` interval is not really random, each star is added one proportional increment closer to the center from `radius + depth`. (this can probably done differently, but I couldn't find how)
```jsx
<Stars
radius={10}         // Radius of the inner sphere (lower bound)
depth={2}           // Depth of area where stars should fit
count={10000}       // Amount of stars
/>
```
Per discussion here: https://github.com/react-spring/react-three-fiber/discussions/440

Stars implementation

---

README.md
src/Stats.tsx

I recently needed to use Stats, but couldn't have it in the top left corner because of existing UI elements, so I made this modification to allow a className to be added to the container so I could target with css.
The only downside is having to use `important` in the css to actually move the damn thing because of the inline styles, but it still seems to be the simplest solution to add a touch of customisation without a load of custom props.

enable optional classname on Stats to allow custom styling

---

src/MeshWobbleMaterial.tsx

Make `time` optional because it's not required for the effect to work

Make `time` property optional in MeshWobbleMaterial so it works in TypeScript

---

src/PositionalAudio.tsx

Stop audio when the component unmounts.  Addresses issue here: https://github.com/react-spring/drei/issues/68

Stop the audio on PositionalAudio unmount

---

.storybook/stories/DeviceOrientationControls.stories.js
README.md
src/DeviceOrientationControls.tsx

This will provide a component, storybook example, and a README.md update. DeviceOrientationControls is one of five missing controls. It could be useful for those wanting to provide mobile interactions and could reduce redundancy for self-implementations of this control.

Added <DeviceOrientationControls/>

---

.npmignore

@drcmda I added this to make sure storybook files are not included in the npm package - since there are actual draco binaries, sounds, etc

Adds .npmignore file to ignore storybook files in npm releases

---

src/StandardEffects.tsx

This adds a console.warn when mounting StandardEffects, since we plan on deprecating it in favour of react-postprocessing
When merging this, release v0.0.071

adds a warning on standardEffects mount

---

package.json
src/Text.tsx

Text sync invalidate

---

.storybook/stories/MeshDistortMaterial.stories.js
.storybook/stories/MeshWobbleMaterial.stories.js
.storybook/stories/Reflector.stories.js
.storybook/stories/Sky.stories.js
.storybook/stories/shaderMaterial.stories.js
package.json
src/abstractions/Line.tsx
src/abstractions/Text.tsx
src/controls/DeviceOrientationControls.tsx
src/controls/FlyControls.tsx
src/controls/MapControls.tsx
src/controls/OrbitControls.tsx
src/controls/TrackballControls.tsx
src/controls/TransformControls.tsx
src/misc/Reflector.tsx
src/shaders/MeshDistortMaterial.tsx
src/shaders/MeshWobbleMaterial.tsx
src/shaders/Sky.tsx
src/shaders/Stars.tsx
yarn.lock

turns out it can't tree-shake, probably because of the extends which are called in global space.
hence, all extends have to go :-S
I added a `?.` on all addEventListeners to keep compatibility with an three version where controls don't have event listeners. Closes #72

making drei treeshakable

---

.storybook/stories/Line.stories.js
src/abstractions/Line.tsx

This PR adds support for the `dashed` prop for Drei's Line abstraction, using the advice from the below comment on the Three `webgl_lines_fat` example.
https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/examples/webgl_lines_fat.html#L236-L239

Support the `dashed` prop in Line abstraction (#103)

---

.storybook/stories/draco.stories.js
src/controls/MapControls.tsx
src/controls/OrbitControls.tsx
src/controls/TrackballControls.tsx
src/controls/TransformControls.tsx
src/loaders/draco.tsx

This removes the requirement of having to ship the `draco` binaries with projects, CDN should be ok for 99% of the users.
It's still possible to specify draco binaries path for both `draco` and `useGLTFLoader`

Draco defaults to Google CDN instead of local

---

.storybook/stories/ContextBridge.stories.js
README.md
src/index.tsx
src/misc/ContextBridge.tsx

Related: https://github.com/pmndrs/jotai/pull/57
This may not work specifically with how `jotai` uses contexts. However, this is a more general use-case Context Bridge that is built to support the standard `React.createContext` api.
Currently, folks have troubles whenever they need to consume context from within a `<Canvas />`. They must go through a few hoops to forward the context into the canvas. This is particularly cumbersome when dealing with multiple contexts -- like most applications use.
This bridge works by reducing an array of contexts that are passed as a prop so that they become nested within each other. The output mimics the typical pattern of:
```tsx
<Context1.Provider>
<Context2.Provider>
<Context3.Provider>
// ....
</Context3.Provider>
</Context2.Provider> …
```

ContextBridge

---

README.md
package.json
yarn.lock

Renamed package to match the new `@react-three/*` namespace.
❗ These packages need to be published at their current version. ❗
❗ I have only renamed the dependencies in the various packages, I have not adjusted the version number. If we bump the version before these PRs get merged, we will need to also change it in each package within the ecosystem. ❗ 
- You may need to add the `--access public` option or something similar since scoped packages are by default private. See https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages for more details
**Note:** Some of these packages have dependencies on each other. If you run into a "package not found" error when attempting to `yarn install`, you might need to run through these steps on a dependent …

renamed package

---

package.json
src/abstractions/Text.tsx
yarn.lock

Included in this update:
- The derived material now automatically picks up changes to the base material; the hacky code for manually forwarding props is no longer needed and has been removed.
- Using materials defined as ES6 classes no longer errors; see #89.
- Text and all its dependencies are now tree-shakeable.

Update to troika-three-text 0.33 and remove the forked r3f-troika

---

package.json

We recently improved the `detect-gpu` package to be more accurate (cf. https://github.com/TimvanScherpenzeel/detect-gpu/pull/24)

Update detect-gpu to 1.5.1

---

.storybook/stories/PointerLockControls.stories.js

i noticed that the TrackballControls story is actually using `<OrbitControls/>`.  I think this is because `<Setup/>` needs `controls={false}` for any *Controls story, otherwise OrbitControls will override any other *Controls.

Issue #120: Add story for PointerLockControls

---

src/useDetectGPU.tsx

none the types in IGetGPUTier are required, but there's no way to pass none of them when props is required in the hook.

#161 Fix useDetectGPU props param typing

---

.storybook/stories/useDetectGPU.stories.js
package.json
src/useDetectGPU.tsx

`detect-gpu` is currently unusable in SSR setups like Next. `3.0` fixes that: https://github.com/TimvanScherpenzeel/detect-gpu/pull/51. This PR is just upgrading the version drei uses.
Fixes #143.

Bump detect-gpu to pick up the SSR fix

---

src/useAspect.tsx

- string literal type for 'type' argument
- 3-number tuple as return type (for compatibility with `<mesh>` scale prop)

Fix types for useAspect

---

rollup.config.js

`sideEffects` only works on the module level. This has very simple rules, described here: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free. It only operates on entire modules. If a module is not imported from, and is marked side effects-free, it is dropped.
The problem is that all the modules in drei are hoisted by Rollup into `index.js`.
Now when a module is imported from, as is the case when someone imports Plane from drei, the job of removing unused code from that module is out of the scope of sideEffects, and instead it falls on terser to remove the unused code from within the module, which it doesn't do for whatever reason.
Rollup has an `output.preserveModules` option, which preserves the re-exports in index.ts, and when an export isn't used it is simply …

Fix tree-shaking

---

src/Text.tsx

In React when you interpolate text with numbers via js escape like this:
```<element>text {someNumberReference}</element>```
the number it is cast to string and processed as a text node. 
It would be nice to do same thing for consistency and general DX.

Allow numbers in Text's children

---

README.md
src/ScreenQuad.tsx
src/index.tsx
src/useFBO.ts

Adds useFBO and ScreenQuad (the gist is stolen from https://github.com/gsimone/ombra).
As mentioned in the updated ReadMe, useFBO creates a `THREE.WebGLRenderTarget` or `THREE.WebGLMultisampleRenderTarget`.
```jsx
const target = useFBO(
// width: 500,  height: 500, 
// width and height are optional and defaulted to the viewport size
// multiplied by the renderer pixel ratio, and recalculated whenever the
// viewport size changes.
{
multisample: true, // if the renderer supports webGL2, it will return a WebGLMultisampleRenderTarget
stencilBuffer: false // you can pass any options supported by THREE.WebGLRenderTarget
} 
)
```

adds useFBO and ScreenQuad

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/--support-question.md

Think it'd be helpful to have some issue templates, gives some initial labels to them so we can see a priority if we're in a rush, also gives more structure. I feel like we ask for a sandbox proposal a lot, so might as well have the template do it for us.

[chore] add templates

---

package.json
src/core/Cloud.tsx
src/helpers/base64.ts
yarn.lock

* resolves #233
Blob is called as part of the Cloud component but Blob is undefined in node, hopefully adding `blob-polyfill` will fix this issue. Releasing on beta first to check in the project I was working in.
If this fix does not work, will have to potentially look at a more manual way of doing what `Blob` does. I did try `fetch-blob` but that wouldn't work with Storybook in the browser.

[fix] Blob is undefined when using SSR

---

README.md
src/core/softShadows.tsx

I've added the correct spelling to the type & set as the default param in `pcss`. It'll try to use the user's `frustrum` spelling & if that's undefined (for new users) then it'll use the correct spelling as deafult.
Also the readme has been updated.

[fix] #242 Frustum has incorrect spelling in softshadows

---

src/core/Line.tsx

You can't continously add points to a lineGeometry as seen in [this sandbox](https://codesandbox.io/s/r3f-line-adding-points-y7utc?file=/src/index.js)
Create new geometry in an effect every time points is changed as suggested by @jugglingcats, because we don't realistically know how many points the user will need we probably shouldn't make a bufferGeometry big enough which is suggested [here](https://stackoverflow.com/questions/31399856/drawing-a-line-with-three-js-dynamically/31411794#31411794). But i'll be honest, i'm not sure if theres some kind of cost to this in the long term, I assume as soon as we replace the geometry the old one is disposed of correctly?
### Related Issues
* resolves #181
https://codesandbox.io/s/drei-181-proposal-vjdtz?file=/src/index.js

feat: #181 – adding points to line

---

README.md
src/core/Environment.tsx

resolves #238 
Added a `scene` prop to `Environment` and added the necessary checks to `useLayoutEffect` to work with passing a custom scene.

feat: add ability to add custom scene as prop

---

CONTRIBUTING.md

Fixes an install error when forking drei and installing locally
change from `npm install` to `yarn install`

fix: change docs to use yarn install instead of npm

---

.codesandbox/ci.json
README.md
src/core/Reflector.tsx
src/materials/MeshReflectorMaterial.tsx
src/materials/index.ts

before (beta stage):
after (stable release):
after (stable release), setting depth to 0:
it appears like depth adds some kind of smudge effect and misses out the clearcoat (roughness 0) spots which should reflect without blur. that was the purpose of the mixBlur factor, it's made to spike the difference in roughness for a more realistic effect. the lower it gets the more will some areas act like clear "mirrors". the higher the value goes, the more will blur take over.

reflectorchanges

---

src/core/DeviceOrientationControls.tsx
src/core/FlyControls.tsx
src/core/TransformControls.tsx

After looking at various controls during (#285) I noticed they all have `target` specified in their types. Only three actually need it/can use it on the Three.js side: `OrbitControls`, `TrackballControls` and `MapControls` (which is OrbitControls underneath).
Removes prop types where they are not applicable/are misplaced. For PointerLockControls, this fix is handled in #285.

fix: remove target prop type in controls where it isn't applicable

---

src/core/shaderMaterial.tsx

adds the clone of uniforms, preventing the use of the same instance
Resolves #190

fix: shaderMaterial uniforms are shared between instances

---

.codesandbox/ci.json
README.md
src/web/Loader.tsx

fix: Makes Loader go from 0 to 100 instead of 0 to 1

---

.storybook/stories/PointerLockControls.stories.tsx
README.md
src/core/PointerLockControls.tsx

When several elements that "activate" the experience are present on the screen (e.g. a 'Enter VR button', a 'Click here to play' button, etc.), it conflicts with PointerLockControl's top-level `document.addEventListener` element binding. 
This PR adds support for binding the control activation to an element found with a selector (e.g. `#instructions`). The default of `document` is unchanged, so this is not a breaking change. I also removed the `target` prop as it has no effect for PointerLockControls (while it's present for most controls, it's only applicable for OrbitControls and TrackballControls - this is addressed in #286)
Not yet ready to merge as there are a few things to discuss, however. 
~~1. Usually all props are spread over into the `primitive`, but in this case the `selector` …

feat: add support for click element selector to PointerLockControls

---

src/core/Reflector.tsx

Any time we wire up a useFrame, furiously null-check refs inside it as an HMR (in Next.js) will trigger an unmount but not before a final frame ticks off, crashing us.

Make Reflector HMR-proof

---

src/core/meshBounds.tsx

Three.js deprecated `getInverse` in r123: https://github.com/mrdoob/three.js/pull/20611#issuecomment-721073246.
Then in a surprisingly aggressive move it looks like they removed it in r124, causing breakages.
The new way to do this is `.invert()`.

fix: updates meshBounds for three.js r124

---

.storybook/stories/Line.stories.tsx
.storybook/stories/MapControls.stories.tsx
.storybook/stories/Shapes.Parametric.stories.tsx
.storybook/stories/TransformControls.stories.tsx
.storybook/stories/useAnimations.stories.tsx
.storybook/stories/useEdgeSplit.stories.tsx
.storybook/stories/useHelper.stories.tsx
README.md
package.json
src/core/CameraShake.tsx
src/core/ContactShadows.tsx
src/core/CurveModifier.tsx
src/core/DeviceOrientationControls.tsx
src/core/Effects.tsx
src/core/Environment.tsx
src/core/FlyControls.tsx
src/core/Line.tsx
src/core/MapControls.tsx
src/core/OrbitControls.tsx
src/core/PointerLockControls.tsx
src/core/Sky.tsx
src/core/TrackballControls.tsx
src/core/TransformControls.tsx
src/core/useEdgeSplit.tsx
src/core/useFBX.tsx
src/core/useGLTF.tsx
src/core/useSimplification.tsx
src/core/useTessellation.tsx
yarn.lock

Tree shaking, transpilation not required anymore,  cleaner code...
Replace three/examples/jsm by three-stdlib
- [ x ] Documentation updated
- [ x ] Updated stories

[Ready !] Use three-stdlib instead of examples/jsm

---

.storybook/stories/OrbitControls.stories.tsx
README.md
src/core/DeviceOrientationControls.tsx
src/core/MapControls.tsx
src/core/OrbitControls.tsx
src/core/PointerLockControls.tsx
src/core/TrackballControls.tsx
src/core/TransformControls.tsx

Demo 
https://codesandbox.io/s/r3f-multi-view-mdnhl?file=/src/Panel.js

feat: Controls can now receive a custom camera as prop

---

src/web/Html.tsx

Simply a 0 is missing, maybe a copy paste issue. But without the 0 the center property isn't working anymore.

fix: Html center bug introduced in #296

---

.storybook/stories/useContextBridge.stories.tsx

I updated the context bridge story to be more friendly. Right now, it is suggesting that we need the redundant syntax of `React.useContext<GreetingContext>(GreetingContext)` which is not true. We can just use `React.useContext(GreetingContext)`.
Also, the destructuring that was being done within the story causes unnecessary confusion as to usage. I updated the property to be `greeting.name` as opposed to `greeting.greeting` so that it doesn't look strange when destructuring is omitted.
This is easier to digest for folks who are newer. In general, storybooks should be more friendly and focused as opposed to being optimized with shorthand.

Updated useContextBridge storybook to be more clear

---

package.json
src/core/MapControls.tsx
yarn.lock

MapControls init and register handlers twice — a bit broken.
A similar problem is illustrated in this CodeSandbox:
https://codesandbox.io/s/r3f-contact-shadow-forked-drey6?file=/src/index.js
Closes #351.
I fixed this on `MapControls` component level by moving side effects to useEffect.
We could do a more direct fix for the root cause — yeet side effects out of OrbitControls — it's a breaking change but three-stdlib doesn't have to be backwards compatible with Three, innit? Side effects in class constructors are 🤮
See 
- https://github.com/mrdoob/three.js/issues/20575
- https://github.com/pmndrs/drei/issues/169
https://user-images.githubusercontent.com/15332326/113441515-bac67580-93ee-11eb-9d22-c55e4b7df387.mp4
https://user-images.githubusercontent.com/15332326/113441531-c023c000-93ee-11eb- …

fix: stop registering dom event handlers in useState in MapControls

---

src/core/OrbitControls.tsx

see issue for details
closes issue #356
Resolves #356  
Changing the name of parameter `enableDampening` to `enableDamping` to match with `three-stdlib` parameter naming
refer to https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts 
- [x ] Ready to be merged
First time contributing to open source so apologies if I did something wrong.

fix: correct parameter within OrbitControls

---

src/core/Environment.tsx

The base URL for environment presets still points at my personal repo, which is unstable.
Changed the URL to point to the pmndrs/drei-assets repo.

fix: use drei-assets URL for environment presets

---

src/core/Environment.tsx
src/core/Stage.tsx
src/helpers/environment-assets.ts

When I tried to use the Stage and pass a different `environment` it just said string and I had to go to GH to fid out what environments existed
Added types to it and imported it

fix(types): add types to enviroment preset

---

src/core/Text.tsx

See issue #379 -- this fixes a memory leak when unmounting `Text` instances.
- Added the `useEffect` cleanup handler to explicitly call dispose
- Removed the leftover `dispose={undefined}`

fix: dispose Text primitive when unmounting to prevent leak (#379)

---

src/core/GizmoHelper.tsx

#358 Background color attached to the scene does not render the `GizmoHelper`.
Added a check in the `GizmoHelper` for any background attached in the scene. If found, it removes the background from the actual scene and adds it to the virtual scene. The background for the actual scene is restored when the `GizmoHelper` is unmounted.
Pending - Background texture attached to the scene overrides the gizmo's material.

#358 fix bg color and gizmo

---

src/core/Line.tsx

memory leak were caused by updating line points
clean up the last frame geometry before drawing new line mesh.

fix: dispose line geom cache when points updating

---

.storybook/stories/HTML.stories.tsx
README.md
src/web/Html.tsx

demo: https://codesandbox.io/s/mixing-html-and-webgl-forked-hpqd3?file=/src/App.js
The current occlusion-behavior is not document nor have we made it public, nor can the transition be controlled/animated. the checkDepth flag that's currently documented did nothing - i think it must have been a left-over. the "occluder" prop was used in the storybook but is not documented.
The changes made in this PR:
- rename occluder to occlude
- occlude can be true in which case the entire scene is taken into account
- or it can be *an array* of refs, it's using intersectObjects instead of intersectObject now
- onOcclude allows the user to control the transition (animations)
[![](https://img.shields.io/badge/-storybook-%23ff69b4)](https://drei.vercel.app/?path=/story/misc-html--html-st) …

feat: html occlude, onOcclude, as

---

.storybook/stories/CameraShake.stories.tsx
README.md
src/core/CameraShake.tsx

Cameras that already have a rotation have it reset to `0,0,0` by `CameraShake`, and `additive` is not a good solution (because you're permanently changing the viewing angle of the camera).
A better fix is to remember the initial rotation of the camera, and _always_ apply the shake vector additively. That way when we decay the shake, the camera resets to its original viewing angle.

fix: Prevent CameraShake from resetting the camera angle

---

src/core/OrbitControls.tsx

I noticed that the `OrbitControls` are being updated even when they're disabled. I'm not sure if this is the desired behaviour, but if I understood correctly the `enabled` prop is meant to be used if you want to manually adjust camera (e.g. change the camera rotation), which is currently impossible.
I've updated the OrbitControls component to only trigger a `controls.update` whenever `controls.enabled` is true.

fix: avoid updating OrbitControls when they're disabled

---

src/web/Html.tsx

https://imgur.com/PMFPuSi
We need to measure the distance from ray origin to elPos instead of distance to camera.
Measuring the distance to camera results in value that is too large.
I changed the distanceTo use the ray origin instead of camera
Not sure what to do for these

fix: corrects isObjectVisible pointDistance

---

src/core/useGLTF.tsx

This PR grants access to the instance of the GLTFLoader. It can be necessary, for example with the plugin system of GLTFLoader.
Example :
```jsx
const gltf = useGLTF('/glb/instance.glb', false, false, (loader) => {
loader.register((parser) => new GLTFInstancingExtension(parser, THREE))
})
```

Callback to extend the gltf loader for GLTF Extensions

---

src/core/TransformControls.tsx

Resolved #444 
Made most props optional for TransformControls, and removed a readonly prop - dragging - based on documentation - https://threejs.org/docs/index.html?q=trans#examples/en/controls/TransformControls
@joshuaellis Please help to review, thanks.

fix: made most props optional for TransformControls

---

package.json
yarn.lock

Update https://github.com/pmndrs/three-stdlib

chore: bump three-stdlib from 2.0.8 to 2.2.0

---

.eslintrc.json
.storybook/stories/Spotlight.stories.tsx
.storybook/stories/useBVH.stories.tsx
src/core/GizmoViewcube.tsx
src/core/Reflector.tsx
src/core/Shadow.tsx
src/core/SpotLight.tsx
src/core/Text.tsx
src/core/meshBounds.tsx
src/core/useAnimations.tsx
src/core/useBVH.tsx
src/core/useCamera.tsx
src/web/Html.tsx

Will enforce `const` when variable is not being re-declared and allow javascript engines for optimizations.
Enabling the `prefer-const` eslint will automatically fix this.
Also did some manual refactoring when I was browsing trough the code. Just removing unused code.

refactor(eslint): enable prefer-const rule

---

src/core/useEdgeSplit.tsx
src/core/useSimplification.tsx
src/core/useTessellation.tsx

So, geometry variable will be overridden anyway.
Removing the `let geometry = new THREE.BufferGeometry()` and replace it by the next variable declaration seems to be working and avoiding to create more unnecessary BufferGeometry's.

fix: avoid creating new Buffer Geometry

---

README.md
src/core/useDetectGPU.tsx

twitter thread: https://twitter.com/lewy_blue/status/1407521953682915328
the current one isn't reliable because it shoots a blank first. since detect-gpu sends a fetch request it should be suspense.
[![](https://img.shields.io/badge/-storybook-%23ff69b4)](https://drei.pmnd.rs/?path=/story/misc-usedetectgpu)
This hook uses [DetectGPU by @TimvanScherpenzeel](https://github.com/TimvanScherpenzeel/detect-gpu), wrapped into suspense, to determine what tier should be assigned to the user's GPU.
👉 This hook CAN be used outside the react-three-fiber `Canvas`.
```jsx
function App() {
const GPUTier = useDetectGPU()
// show a fallback for mobile or lowest tier GPUs
return (
{(GPUTier.tier === "0" || GPUTier.isMobile) ? <Fallback /> : <Canvas>...</Canvas>
<Suspense fallback={null}>
<App />
```

fix: useDetectGPU is fetch-based and therefore should use suspense

---

src/core/OrbitControls.tsx

This should allow a prop specifying an optional pointer event target DOM node passed to OrbitControls, e.g. `<OrbitControls domElement={canvasRef.current} />`. With the latest consolidation in three.js to use pointer events, this is important for the controls to work properly on mobile (see https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L102). 
It would be even better if a ref to @react-three/fiber `<Canvas/>` could be passed in implicitly by default, but I don't think it's exposed anywhere — suggestions welcome.

fix: pass domElement to OrbitControls

---

package.json
yarn.lock

chore: bump three-stdlib to 2.3.1

---

.storybook/stories/useDetectGPU.stories.tsx

The live sample of Misc/useDetectGPU page in the docs ( https://docs.pmnd.rs/drei/misc/use-detect-gpu ) was broken, as shown in the image below.
Added <React.Suspense fallback=...> based on the error messages.

fix: broken Misc/useDetectGPU page in the docs

---

.storybook/stories/Shapes.Tube.stories.tsx

The live sample of Shapes/Tubes page in the docs ( https://docs.pmnd.rs/drei/shapes/tube ) was broken, as shown in the image below.
I modified the file based on `TubeGeometry` page in the three.js docs ( https://threejs.org/docs/#api/en/geometries/TubeGeometry ) . I replaced what was a function with a class.

fix: broken Shapes/Tube page in the docs

---

src/core/DeviceOrientationControls.tsx
src/core/FlyControls.tsx
src/core/MapControls.tsx
src/core/OrbitControls.tsx
src/core/PointerLockControls.tsx
src/core/TrackballControls.tsx
src/core/TransformControls.tsx

With vanilla `OrbitControls` I can listen for `change`, `start`, and `end` events. These are useful to prevent other interactions (e.g. hovers, clicks) from occurring while the camera is moving. For example, 
``` js
const controls = new OrbitControls(camera, domElement); 
let timeoutId;
controls.current.addEventListener('change', () => {
setOrbitControlsInUse(true);
console.log('change');
if (timeoutId) {
clearTimeout(timeoutId);
}
timeoutId = setTimeout(() => {
setOrbitControlsInUse(false);
}, 150);
});
```
To match the capabilities of vanilla controls I added `onChange`, `onStart`, `onEnd` props to `OrbitControls`. These each take and optional THREE.Event argument:
``` js
const onStart = (e) => {
console.log("Camera interaction started", e);
}
const onEnd = (e) => {
console.log("Camera …
```

Feat: add onStart, onEnd, onChange props to OrbitControls

---

src/core/Reflector.tsx

Currently, Reflector does not render properly in XR due to it not pulling from the proper camera.
I've added the changes that were made in [three.js proper](https://github.com/mrdoob/three.js/blob/master/examples/jsm/objects/Reflector.js#L158), which disables XR on the renderer before performing the render and restores it to its previous state afterwards.

Fix Reflector rendering in XR

---

src/web/Html.tsx

There was an unecessary pointerEvents styles on one of the child divs of the Html component
Removed the pointerEvent style
NA
resolves issue: #460

fix: pointerEvents for Html

---

src/web/Html.tsx

Importing drei component from the root (e.g. `import { OrbitControls } from '@react-three/drei'`) will fail if `react-dom` isn't installed in the app. This error is confusing (cause it's not directly connected with the import), plus `react-dom` is an optional dependency and root imports should not require optional deps IMO.
I've used a `require` call that will silently fail if no `react-dom` is installed. However when Html component will be used, it'll throw warnings to the console telling the user to install it
It's a draft cause I'm not entirely sure it'll work in all environments (although I've used this technique previously, e.g. in presentation library https://github.com/saitonakamura/presa/blob/master/packages/blocks/src/code/index.tsx#L22) and I'm not sure whether it's too hacky …

feat(Html): allow import from root without react-dom

---

.storybook/stories/useTexture.stories.tsx

To have a running example that fixes https://github.com/pmndrs/drei/issues/530
After the updates in the documentation on:
https://github.com/pmndrs/drei/commit/320384e444d2e03aa92397855ac3c083d80af012
https://github.com/pmndrs/drei/commit/f34aa0049d73a2357f5b2afc22c2c3e6565ff373
Adds a texture loader by key/obj to the Storybook example.
Thanks!

docs: adding key/obj texture loader example on storybook

---

src/web/Html.tsx

hi! just a small nit.
Removing the unnecessary else clause and keeping it consistent with other functions like `objectZindex`

chore: remove unnecessary else

---

.storybook/stories/PointerLockControls.stories.tsx
README.md
src/core/PointerLockControls.tsx

PointerLockControls already supports an optional `selector` prop, which allows PointerLockControls to lock by clicking other elements than document. The problem with current solution is that it's not possible to use multiple elements as selectors.
This PR expands the current functionality by adding click event listeners to all elements matching the given selector, not just one.

Feat/add support for multiple selector elements in PointerLockControls

---

README.md
src/core/Instances.tsx
src/core/PointMaterial.tsx
src/core/Points.tsx
src/core/index.ts
src/helpers/Position.tsx

instancing is a sealed structure. it can't be easily and effectively tied to nested reactive state, you can't form components that perform individual tasks, you can't share, compose or outsource behaviour. not even to mention events.
```jsx
<Points>
<pointsMaterial />
<Point position={[1, 2, 3]} color="red" onClick={onClick} onPointerOver={onPointerOver} ... />
// As many as you want, make them conditional, mount/unmount them, lazy load them, etc ...
```
```jsx
<Instances>
<boxGeometry />
<meshStandardMaterial />
<Instance position={[1, 2, 3]} rotation={[Math.PI / 3, 0, 0]} scale={2} color="red" onClick={onClick} ... />
// ...
```
demo: https://codesandbox.io/s/r3f-points-czhxx?file=/src/App.js
advantages:
- declarative
- single draw call
- render optimized (renders only when needed)
- …

feat: declarative instancing

---

src/core/CameraShake.tsx

'OrbitControls' is declared but its value is never read.ts(6133)
Remove never read import.

chore: remove never read import

---

README.md

Realized that `OrthographicCamera` is the only one without no code example in the Readme.
nit: Also removing whitespace from the same file.
Thanks!

docs: add OrthographicCamera code example to readme.

---

src/core/useHelper.tsx

`useHelper` currently breaks when using static helpers which don't expose update methods (as seen in #551).
This PR updates `useHelper` to ignore updates for helpers which don't supply update methods.
Here's a recreation of the issue with changes from this PR: https://codesandbox.io/s/amazing-ives-vmq9z?file=/src/App.js.

fix(useHelper): skip updates on static helpers

---

src/core/useGLTF.tsx

With https://github.com/pmndrs/three-stdlib/pull/84, we can re-use the same `MeshoptDecoder` as well as regain sanity with the removal of the recent console log.
This PR conditionally creates or re-uses `MeshoptDecoder` from `three-stdlib` to ensure backwards compatibility, as proposed in #501.

fix(useGLTF): backwards compat for three-stdlib

---

README.md

Resolves #563.
Added explanatory comments to example in docs, to make it clearer how to use the context bridge correctly.

docs: clarify provider requirements for useContextBridge

---

.storybook/stories/ScrollControls.stories.tsx
src/web/ScrollControls.tsx

Fixes #600 
Removed the `raycaster.computeOffsets` override. Not sure why it was added, however, appears to fix the problem.
- ~Documentation updated~

fix: pointer events offset for ScrollControls

---

.storybook/stories/Segments.stories.tsx
README.md
src/core/Segments.tsx
src/core/index.ts

* Using many separated Line components is inefficient, as each one of them uses a new geometry.
* Line components cannot be separated into segments (to share the geometry).
* Proposed are 2 components: Segments (a wrapper), and Segment, a component to add the segment to the geometry. 
* Segments/Segment components share the geometry in a declarative way (similar to Instances/Instance but for segments).
```jsx
<Segments limit={1000}>
<Segment start={[0,0,0]} end={[10,10,0]} color={[1,1,1]} />
</Segments>
```

feat: add fast declarative segments with single geometry.

---

.storybook/stories/useGLTF.stories.tsx
src/core/useGLTF.tsx

Fix #615 - Multiple DRACOLoader instances are known to cause problems on iOS: mrdoob/three.js#22445
* dracoLoader instance is now cached using local variable in `useGLTF`
* updated draco lib CDN version to 1.4.3
* fixed storybook types

fix: cache DRACOLoader instance in useGLTF

---

package.json
src/core/Instances.tsx
src/web/ScrollControls.tsx
yarn.lock

See https://github.com/pmndrs/three-stdlib/pull/95.
Bump up three-stdlib version to 2.5.6

fix: bump up three-stdlib version to 2.5.6

---

.storybook/stories/Segments.stories.tsx
README.md
src/core/Segments.tsx

Segment doesn't allow for string color and cannot use both refs and props simultaneously.
Segment now accepts string color. Better ref handling, now we can mix both refs and props.

fix: better segment refs, support for string segment color

---

README.md

According to https://github.com/pmndrs/react-three-fiber/blob/master/markdown/changelog.md#removal-of-useresource, it seems we should use `useState` instead of `useResource`.
Same fix in the website repo https://github.com/pmndrs/website/pull/200.
Changed `useResource` to `useState` in the conrols section

docs: change useResource to useState in readme

---

.husky/commit-msg
.husky/pre-commit

Not everyone wants to install `yarn` globally on their system. The commit hooks assume `yarn` is installed globally and fail when trying to commit. `npm` and `npx` work just fine for this task and do not need to be installed separately. If you change package managers (to `pnpm` for example) you won't need to update your commit hooks.
- Use `npx --no-install` for running devDependencies directly
- Use `npm run` for running scripts defined in the `package.json`

fix: do not require a global install of yarn for commit hooks

---

src/web/ScrollControls.tsx

`ScrollControls` doesn't allow for any customization of the root container. In some cases (say, when working with `react-three-next`, which creates a `dom` root with a z-index that overlaps and breaks `ScrollControls`) we need to override some style properties.
Just added a quick `style` field that we copy onto the root div style.

Allow custom styles for root scroll container

---

src/core/TransformControls.tsx
src/web/ScrollControls.tsx

⚠️ This PR should be merged after https://github.com/pmndrs/drei/pull/654
Transform Controls allows the user to pass the target object in 2 ways:
* as an object property
* as a children
If passed as a property, children will be undefined and generate a TS error.
Make the children property optional.

fix: transform controls children type

---

src/core/Bounds.tsx

If call `bounds.refresh` with unmounted group it will crash because ref wasn't checked for undefined.
Added check for undefined before using `ref.current`

Check if group ref is undefined before accessing it in Bounds.tsx.

---

.github/ISSUE_TEMPLATE/--support-question.md
README.md

The link to the poimandres discord in the support question template is invalid 
Always use the poimandres discord vanity URL -- https://discord.gg/poimandres
Fixes #667

chore: use poimandres discord vanity URL

---

.github/ISSUE_TEMPLATE/---bug-report.md
sandboxes/bug-report-template-starter/package.json
sandboxes/bug-report-template-starter/public/index.html
sandboxes/bug-report-template-starter/src/index.jsx
sandboxes/bug-report-template-starter/src/styles.css

The sandbox from the link in the bug report template is broken and out of date.
Fixes #670
Use githubbox.com to open the bug-report-template-starter from this repo.
Here's what it looks like from my branch -- https://githubbox.com/bjornstar/drei/tree/bug-report-template-starter/sandboxes/bug-report-template-starter

chore: use sandbox from repo for bug report template

---

.storybook/stories/useTessellation.stories.tsx
src/core/AdaptiveDpr.tsx
src/core/AdaptiveEvents.tsx
src/core/ArcballControls.tsx
src/core/Bounds.tsx
src/core/CameraShake.tsx
src/core/Center.tsx
src/core/CubeCamera.tsx
src/core/Environment.tsx
src/core/GizmoHelper.tsx
src/core/MeshReflectorMaterial.tsx
src/core/OrbitControls.tsx
src/core/Preload.tsx
src/core/Reflector.tsx
src/core/Stage.tsx
src/core/TrackballControls.tsx
src/core/useAnimations.tsx
src/core/useContextBridge.tsx
src/core/useFBO.tsx
src/helpers/useEffectfulState.tsx
src/web/Html.tsx

We turned off `react-hooks/exhaustive-deps` in #648 but left a bunch of comments in the code disabling it
Removed all comments that disable the eslint rule `react-hooks/exhaustive-deps` as it's already disabled

Remove eslint-disable-next-line react-hooks/exhaustive-deps comments

---

src/core/Bounds.tsx

When bounds is used with orthographic trackball controls, camera should be placed upon the trackball sphere on bounds refresh, otherwise camera might be too near to the objects and clipping view might appear.
Put camera on sphere in Bounds.refresh method

Refresh camera pos

---

README.md
src/web/Html.tsx

This adds the ability to set a class name on the outer element so that it can be addressed by CSS selectors.  This is in response to [this feature request](https://github.com/pmndrs/drei/issues/679) that I made. 
The use case that prompted me to make this change was that when I select the 3D element the HTML corresponds to, I want the z-index of that element to come to the top layer no matter what.
I added a wrapperClass attribute to HTML, which takes a string. 
A useEffect hook updates the className on the main el.
- [ x] Documentation updated
Thanks, this is my first ever pull request on Github, let alone drei - so please help guide me through this if I have done something wrong. One question I had is whether I should clean up in the useEffect with a return, it …

feat: add wrapperClass to HTML

---

package.json
yarn.lock

- #680 
- Update caniuse-lite (fixes #680)
- Add `yarn` as a devDependency

chore: update caniuse-lite

---

src/core/Instances.tsx
src/helpers/Position.tsx

https://codesandbox.io/s/floating-instanced-shoes-forked-u6z5e?file=/src/App.js:786-949
Currently raycast on drei/instances are a forwarding hack, the main instance collects event props from the instances and forwards click handlers back into them. This has several disadvantages, there is bubbling, it cannot be grouped, overall it is not part of r3f's event system and merely works as an appendage.
This solution moves events into the individual instances raycast method, which takes the parents (THREE.InstancedMesh) geometry and tests the ray against it. Now these events behave like any other.
Instances normally do not have bounds because they are virtual, only the main THREE.InstancedMesh has bounds. The instance is an empty object3d with nothing in it, it's just being used to track …

fix: handle instance events at the raycast

---

src/core/MeshReflectorMaterial.tsx

Hey folks, just a tiny fix for a useCallback dependencies issue.
Was trying to use this with my own PerspectiveCamera + makeDefault prop, and the reflection was not updating.
Added latest  `camera` value to useCallback deps for beforeRender.

fix: always use current default camera in MeshReflectorMaterial

---

src/core/TransformControls.tsx

Just like in OrbitControls through the connect method, this PR allows specifying another domElement with TransformControls.

TransformControls: Override the domElement

---

README.md
src/web/PresentationControls.tsx

Makes the cursor style of PresentationControls optional behind a `cursor` prop. Also moves styles to the gl canvas instead of the entire page.

feat(PresentationControls): make cursor style optional behind prop

---

.prettierignore
.storybook/stories/Adaptive.stories.tsx

Super minor, but I'd like to apply some best practices to our storybooks:
- Only import what you are using
- Use `import type` when only the type is being used
- Avoid casting (ie. `as`) where possible
The first two help with tree shaking and keeping bundle sizes down.
The latter is typically used when types are incorrect or incomplete and tends to cause runtime problems.
- Added `storybook-static` to `.prettierignore` it's the output directory for `npm run storybook-build`
- Applied best practices to the Adaptive storybook

chore: apply best practices to Adaptive storybook

---

src/core/Stats.tsx

The library stats.js is imported but we do not use it, instead, three/examples is being used

fix: use npm instead of three/examples

---

.storybook/tsconfig.json

The config for the library and the storybook are the same, no need to have a separate config
Removed the `tsconfig.json` file from the `.storybook` directory

chore: remove .storybook/tsconfig.json it is unused

---

.storybook/stories/ArcballControls.stories.tsx
.storybook/stories/CurveModifier.stories.tsx
package.json
src/core/ArcballControls.tsx
src/core/OrbitControls.tsx
yarn.lock

three-stdlib v2.7.2 includes FontLoader & TextGeometry which were moved out of three core in r133
- Updated the CurveModifierStory to use FontLoader from three-stdlib
- Added ArcballControlsStory to validate the new version of the ArcballControls
- Updated OrbitControlsStory to use Controls instead of Knobs

feat: update three-stdlib to v2.7.2

---

src/core/CubeCamera.tsx
src/core/MeshReflectorMaterial.tsx
src/core/Reflector.tsx

Related: https://github.com/pmndrs/three-stdlib/pull/115.
Removes usage of RGBFormat with three r137. Notably, `Material.format` was also depreciated for `Material.alphaWrite`, but we make no use of it here.

fix(core): remove usage of RGBFormat

---

.storybook/stories/Reflector.stories.tsx
README.md
src/core/MeshReflectorMaterial.tsx

Allow reflective surfaces to be offset from the object's origin. Resolves #721.
Added a simple `reflectorOffse: number` prop to the MeshReflectorMaterial component. The `reflectorWorldPosition` is then translated that distance, in the normal (z) direction.
Refer to #721 for screenshots of the problems being solved. Here are corresponding screenshots showing the resolution:
1. When viewed from side-on, objects are now reflected perfectly in the offset mirror:
2. When view from side-on, the reflection is no longer clipped:

feat: add reflectorOffset to MeshReflectorMaterial

---

README.md

I had some confusion about the Instances component and the proper way to use it with regards to CPU overhead.
I added a note to the Instances section of the readme letting users know the declarative method comes with a CPU overhead and to use THREE.InstancedMesh for situations like foliage. I linked another sandbox by Paul to demonstrate the difference.

Doc instance update

---

.storybook/stories/useHelper.stories.tsx
README.md
src/core/useHelper.tsx

```
useHelper(false,...) 
```
removes the helper from the scene, so helpers can now be toggled
- closes #334 
This is the simple solution to avoid a breaking change

feat: makes useHelper togglable by passing first prop as false

---

.storybook/stories/Billboard.stories.tsx
.storybook/stories/Text.stories.tsx
.storybook/stories/useContextBridge.stories.tsx
.storybook/stories/useDetectGPU.stories.tsx
README.md
package.json
src/core/Text.tsx
src/core/useDetectGPU.tsx
src/core/useMatcapTexture.tsx
src/core/useNormalTexture.tsx
yarn.lock

`<Text />` previously loads async assets but wasn't integrated into suspense, therefore it suffered from FOUC.
according to @lojjic assets can be preloaded via preloadFont, this was wrapped into a suspense call.
i removed all notions of (deprecated) use-asset and used suspend-react. it's smaller (500bytes), and typescript can completely infer results. this will be used by r3f v8 by default but it doesn't hurt to already use it here.

fix: text fouc, use suspend-react instead of use-asset

---

.storybook/stories/useHelper.stories.tsx
src/core/useHelper.tsx

Currently, the rest arguments of useHelper are typed as `any[]`, which can be improved upon.
Infer the types of the rest args from the Helper type.

feat: better type inference for `useHelper` hook

---

src/core/ContactShadows.tsx

scene.overrideMaterial is being cleared in ContactShadows's render cycle.
Is it intentional?

fix: keep overrideMaterial while using ContactShadows

---

README.md

Fix syntax error in README.md `PresentationControls` example.

fix: syntax error in README.md PresentationControls example

---

src/core/Sampler.tsx

Change import of MeshSurfaceSampler to `three-stdlib`

fix: changes import of MeshSurfaceSampler to `three-stdlib`

---

src/core/Sampler.tsx

this PR fixes the "Cannot use import statement outside a module"

fix: changes import of MeshSurfaceSampler to 'three-stdlib' without sub-package

---

src/web/ScrollControls.tsx

ScrollControls doesn't react to `enabled` prop changes on re-render, instead it keeps the initial value passed on the first mount.
Added the `enabled` prop to the ScrollControls useEffect dependencies array.
It didn't seems to be necessary to add any extra change on docs/storybook since this behavior is likely to be expected.
(btw, this is my first OSS PR so I might have messed something up with the commit message, please guide me if you need me to change something :) thanks!)

fix: Add 'enabled' to ScrollControls useEffect deps

---

src/core/Image.tsx

The image abstraction prop types don't allow for scale as an array, but the component implies that this should be allowed.
```ts
Array.isArray(scale) ? [scale[0], scale[1]] : [scale, scale]
```
Added [number, number] as an option.

fix(Image): scale typing to allow array

---

src/core/Stats.tsx

The `Stats` component has a `className` property for styling the component. Unlike all the React DOM built-in components, it only allowed a single class to be passed. The following raised an exception:
```jsx
<Stats className="class-a class-b" />
```
The `Stats` component has been reworked to split the passed `className` by whitespace and individual classes added to the underlying DOM element.
Tested manually through the Stats storybook.
Closes https://github.com/pmndrs/drei/issues/789.

feat: support multiple css classes on Stats component

---

package.json
src/web/ScrollControls.tsx
yarn.lock

I found out that ScrollControls was broken on the Y axes. Based on this example running the last version of `drei`: https://codesandbox.io/s/horizontal-tiles-forked-w3ux99
**The issue:** The tiles hover is being triggered even if you are not hovering them on the Y axes. And it was also triggering hover on the wrong coordinates on the drei's production storybook.
https://user-images.githubusercontent.com/43894343/161403840-aca9bec5-b48c-4b58-be93-46ec3c645090.mov
I updated:
- The client coordinates axes variable on the offsetY calculation to be `clientY` instead of `clientX`
- The target element on both `x` and `y` offset calculations.

Bugfix: ScrollControls events

---

README.md
src/core/index.ts
src/web/View.tsx
src/web/index.ts

<p>
<a href="https://codesandbox.io/s/bp6tmc"><img width="20%" src="https://codesandbox.io/api/v1/sandboxes/bp6tmc/screenshot.png" alt="Demo"/></a>
<a href="https://codesandbox.io/s/1wmlew"><img width="20%" src="https://codesandbox.io/api/v1/sandboxes/1wmlew/screenshot.png" alt="Demo"/></a>
</p>
Views use gl.scissor to cut the viewport into segments. You tie a view to a tracking div which then controls the position and bounds of the viewport. This allows you to have multiple views with a single, performant canvas. These views will follow their tracking elements, scroll along, resize, etc.
It is advisable to re-connect the event system to a parent that contains both the canvas and the html content. This ensures that both are accessible/selectable and even allows you to mount controls or …

feat: view draft

---

src/core/Line.tsx

This fixes a Typescript typing problem.
The `LineProps` type defined for the `Line` component declares the type of `vertexColors` to be `Array<Color | [number, number, number]>`, which is what the actual code expects.  However, `LineProps` also includes the type `LineMaterialParameters`, which defines a conflicting definition of `vertexColors` (indirectly, in THREE's `MaterialParameters`): `vertexColors?: boolean | undefined`
This results in an incorrect, somewhat nonsensical type for `vertexColors` of `(([number, number, number] | Color)[] & boolean) | undefined`.  Code in a Typescript project that provides `Line` with a validly typed prop value for `vertexColors` will be flagged as having the incorrect type.
I have updated the type definition of `LineProps` to Omit the `vertexColors` …

fix: omit LineMaterialParameters.vertexColors type from LineProps type

---

.storybook/stories/Line.stories.tsx
package.json
yarn.lock

Right now using the Line component with the latest Three r139 yields a type error, since the `alphaWrite` prop is not present anymore.
- `three-stdlib`, `three`, and `@types/three` are now to the latest version
- An import error was fixed in the Line stories

chore: Updates three and stdlib to fix Line component

---

.storybook/stories/Segments.stories.tsx
src/core/Segments.tsx

The current loading times of the Segments story are pretty slow, since it's calling `useFrame` for each object. Unfortunately this is slow in r3f, since it has to update the internal zustand state multiple times. I think a better example for performance can be shown by using an array of refs and a single useFrame.
During this process I also found that some user-facing types of the component were wrong, so I corrected them.
(see above)

fix: Type and story fixes for Segments

---

.storybook/stories/Float.stories.tsx
README.md
src/core/Float.tsx

I wanted the ability to limit the floating of an object (on the y axis) to a specific range of positions
I added the props minPosition and maxPosition to <Float />. Also added a storybook entry.

feature: adds range clamps to Float

---

README.md

I made a small change in the Readme file to fix a broken link.

fix broken `BBAnchor` story url

---

src/core/Effects.tsx

#935 
Changes the implementation of `<Effects>` to check for non-null children before cloning them. This enables effect composition through conditional rendering:
```jsx
export const RenderPipeline = ({
bloom = false,
toneMapping = false,
vignette = false
}) => (
<Effects>
{bloom && <unrealBloomPass args={[new Vector2(256, 256), 2, 0.05, 1]} />}
{toneMapping && <adaptiveToneMappingPass args={[true, 256]} />}
{vignette && <shaderPass args={[VignetteShader]} />}
</Effects>
)
```
`<Effects />` now checks for `el` being truthy before it is passed to `React.cloneElement`.
Fixes #935

fix: allow <Effects> children to be null

---

src/core/useHelper.tsx

With React 18 types you need to pass `null` to `useRef` for it to be a "MutableRefObject", this causes some issues with the `useHelper` hook currently.
```jsx
export function DirectionalLight(
props: JSX.IntrinsicElements['directionalLight'],
) {
const { debug } = useContext(LightContext)
const ref = useRef<ThreeDirectionalLight>(null)
const cameraRef = useRef<Camera | null>(null)
useEffect(() => {
cameraRef.current = ref.current?.shadow.camera ?? null
}, [])
// first arg fails TS checks with Argument of type 'false | MutableRefObject<Camera | null>' is not assignable to parameter of type 'MutableRefObject<Object3D<Event> | undefined> | Falsy'.
useHelper(debug && cameraRef, CameraHelper)
return <directionalLight ref={ref} {...props} />
}
```
Allow `null` value of the ref

fix(useHelper): allow ref value to be null

---

src/core/GizmoHelper.tsx

closes #860 
Just need to reset the `up` vector of the main camera after the animation is complete. This line suggests that the up vector is quite important with OrbitControls 
https://github.com/mrdoob/three.js/blob/0c26bb4bb8220126447c8373154ac045588441de/examples/jsm/controls/OrbitControls.js#L12

fix: GizmoHelper messing up OrbitControls rotation axes

---

src/helpers/glsl/GroundProjection.frag.glsl

As referenced in issue #947 the ground rendering of the Environment is broken if the camera enters the radius and looks up.
My solution is to use a back facing check in the disk intersection function to avoid using the wrong intersection point (the one behind the camera if it looks up).

fix: the ground rendering of the Environment component

---

.storybook/stories/GizmoHelper.stories.tsx
src/core/GizmoHelper.tsx

I wanted the option to center the view cube on the bottom center instead of in the corner. while I was at it I made it so you could center on the sides as well. So now things like right-center or center-bottom work.
I added more options to the alignment field of the viewCube. 
- [ x] Documentation updated <- there wasnt documentation to show the aligment flags
- [ x] Storybook entry added <- put some options in the GismoHelper.stories.tsx

feat: add center as an option for viewcube

---

.storybook/stories/Line.stories.tsx
README.md
src/core/CatmullRomLine.tsx
src/core/index.ts

I was working on a project using CatmullRomCurve3 instances and I created a custom abstraction component. Since abstractions exist for CubicBezierCurve3 and QuadraticBezierCurve3, but not CatmullRomCurve3, I figured this component may be useful to others. Resolves #456 
Added new abstraction for CatmullRomCurve3, `CatmullRomLine`, based on `CubicBezierLine` and `QuadraticBezierLine`
Within the `CatmullRomLine` abstraction, I added a vertexColor interpolation calculation which automatically generates an interpolated vertexColor array dynamically based on the number of `segments` specified in props. If this interpolation is considered useful, and seeing as the `segments` approach is also used in the other Line abstractions, this calculation could be extracted into some sort of utility …

feat: add abstraction for CatmullRomCurve3

---

src/web/PresentationControls.tsx

resolves #954 `PresentationControls` `snap`'s type can be `SpringConfig`
Appended `@react-spring/core`'s SpringConfig to the `snap` type.
```
snap?: Boolean
```
```
snap?: Boolean | SpringConfig
```

fix: `PresentationControls` `snap`'s type can be `SpringConfig`

---

src/core/Text3D.tsx

Fixes https://github.com/pmndrs/react-three-fiber/issues/2382 by filtering out text contents from the scene graph.

fix(Text3D): filter out text contents from R3F scene-graph

---

.storybook/stories/CameraShake.stories.tsx
.storybook/stories/CubeCamera.stories.tsx
.storybook/stories/Environment.stories.tsx
.storybook/stories/Float.stories.tsx
.storybook/stories/MapControls.stories.tsx
.storybook/stories/useBVH.stories.tsx
src/core/ContactShadows.tsx
src/core/Reflector.tsx
src/core/RoundedBox.tsx
src/core/shapes.tsx

Deprecates usage of `*BufferGeometry` aliases since https://github.com/mrdoob/three.js/pull/24352.

fix: deprecate usage of *BufferGeometry aliases

---

src/core/ContactShadows.tsx

When you use `<ContactShadows />` a unexpected *console.log* output appears. This PR resolves #1004 
Remove the `console.log(shader.fragmentShader)` in **line 81** of the file in *drei/src/core/ContactShadows.tsx*.

fix: contact shadows console.log output fix #1004

---

src/core/Center.tsx

Trying to center text based on the screen width and hoping this will help.
Added an onCentered callback that contains some bounds to check against.

feat: added onCentered callback in the useLayoutEffect

---

src/core/shapes.tsx

Related: #1007 
Elements were being created as *BufferGeometry instead of *Geometry.
See #1034.
Just a tiny tweak to ensure the function that creates meshes uses *Geometry instead of *BufferGeometry.

fix: complete *BufferGeometry alias deprecation

---

src/core/Line.tsx

Resolves #1036 
`LineProps.color` stop accepting string and only accepted number after `"@react-three/drei": "9.22.6"`.
This should allow `LineProps` to accept `ColorRepresentation` (`string`, `number` or `Color`) again.

fix: change LineProps.color to be ColorRepresentation

---

src/core/pivotControls/AxisArrow.tsx
src/core/pivotControls/AxisRotator.tsx

Added invisible meshes for raycaster picking (as in [`TransformControls`](https://github.com/mrdoob/three.js/blob/68daccedef9c9c325cc5f4c929fcaf05229aa1b3/examples/jsm/controls/TransformControls.js#L1129)).
Picking gizmos by their thin lines is not really convenient, especially for touch devices.
It can be tweaked and improved in the future, but for now that is kind of must-have feature.
Is it ok?
Related: https://github.com/pmndrs/drei/pull/933#issuecomment-1226039814

feat: add hit areas to pivotcontrols

---

src/core/Text.tsx

`TextMeshImpl` does not have a type definition so the declaration files fail to type-check with this error:
```
node_modules/@react-three/drei/core/Text.d.ts:49:24 - error TS2304: Cannot find name 'TextMeshImpl'.
49     onSync?: ((troika: TextMeshImpl) => void) | undefined;
~~~~~~~~~~~~
```
Replace the use of `TextMeshImpl` as a type with `any` since that's what it would be implicitly.

fix(types): import TextMeshImpl does not have a type definition

---

src/core/shaderMaterial.tsx

resolves #1055
`super()` was called only with the `uniforms`, `vertexShader`, and `fragmentShader` properties. I added constructor parameters to it.

fix: allow passing constructor params to materials created with shaderMaterial (#1055)

---

src/core/RenderTexture.tsx

Properly extends `RenderTexture` props to match a native element, namely `attach`.

fix(RenderTexture): use texture JSX props

---

src/core/Sparkles.tsx

Modules should not import from flatbundles that they are a part of.

fix(Sparkles): remove circular dependency

---

src/web/View.tsx

Fixes #1059 by wrapping the inner portal inside of a fragment. This comes from a typing issue in R3F's `createPortal`, fixing this downstream in https://github.com/pmndrs/react-three-fiber/pull/2550.

fix(View): wrap portal in fragment

---

src/core/Image.tsx

Fixes #869 by overwriting meshs' `scale` prop as described in https://github.com/pmndrs/drei/pull/879#issuecomment-1112711608.

fix(Image): override scale prop

---

src/core/Instances.tsx

Fixes #816, partial implementation of #1075.

feat(Instances): expose types, ref

---

src/web/KeyboardControls.tsx

The `onChange` props in `KeyboardControlsProps` is missing a `?` operator. As a result, it forces users to add `@ts-ignore` rule, or a dummy `onChange={() => {}}`. The dummy listener solution has a negative consequence:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```
which is triggered when the users type any key.
The fix is an optional `?` operator after `onChange`.
Based on the following comment:
`/** Optional onchange event */`
I think that this fix is consistent with how the API was designed.

fix: make onChange an optional props in KeyboardControls

---

src/core/useIntersect.tsx

Fixes #1057 by creating a ref-callback that keeps the current `onChange` callback live.

fix(useIntersect): call live callback

---

package.json
yarn.lock

#1064 introduced a regression where `three-stdlib` was pinned to an exact version.

fix: don't pin deps

---

src/core/TransformControls.tsx

Prefers ref-callbacks to play nice with batched updates in React since the handler effect is otherwise rerunning with parent state updates.

fix(TransformControls): prefer refcallbacks for handlers

---

README.md

chore(docs): typo in README "width" and "foward"

---

.storybook/stories/PresentationControls.stories.tsx
README.md
src/web/PresentationControls.tsx

really nice job with those helpers, i really like your projects!
easily disabling the controls by props wasn't possible before.
i am using a early return to disable the controls. is there a better way?
this pr removes the cursor as well as skips some calculations while dragging if enabled is set to false.
I went ahead and added a story for this component as well :)

feat: add enabled prop to PresentationControls

---

.storybook/stories/Svg.stories.tsx
README.md
src/core/Svg.tsx
src/core/index.ts

So is easy to render SVG stuff.
Added an `Svg` r3f component that can render SVG data in three.
Is a wrapper around the [svg loader](https://threejs.org/examples/?q=sv#webgl_loader_svg) demo. 
[Storybook PR link](https://drei-git-fork-rodrigohamuy-feat-svg-pmndrs.vercel.app/?path=/story/abstractions-svg--svg-st)

feat: add Svg component

---

README.md

Updated README file based on a commit that updated the type of \<Mask\/\>'s children prop. #959 
Changed the line from
```ts
children: (spread: MaskSpread) => React.ReactNode | React.ReactNode
```
to
```ts
children: ((spread: MaskSpread) => React.ReactNode) | React.ReactNode
```

docs: correct <Mask/>'s children type in README

---

src/core/TransformControls.tsx

Change type of TransformControlsProps mode & space from string to union type for better props value suggestion in code editor
Change props type mode & space of `<TransformControls />` components from string to union type.
Union value get from:
https://threejs.org/docs/#examples/en/controls/TransformControls.mode
https://threejs.org/docs/#examples/en/controls/TransformControls.space

fix: change TransformControlsProps mode & space to union type

---

.storybook/stories/KeyboardControls.stories.tsx
README.md
src/web/KeyboardControls.tsx

- `KeyboardControlsEntry` wasn't exported, so it wasn't easy to define this outside the component.
- `useKeyboardControls()` always returned `any` because TS couldn't resolve the function, which is not fun for TS devs.
- Added `KeyboardControls` story: `/?path=/story/controls-keyboardcontrols--keyboard-controls-st`
- `KeyboardControlsEntry` is now exported and is optionally generic.
- `useKeyboardControls()` now returns the correct types for each case, because the function overloading declarations have been added.
- `useKeyboardControls()` now supports generics, so you can pass which keys you are expected to use.
For example, consider you have a `Controls` enum, you can now pass that as a generic and get the correct types for all case scenarios:
```tsx
enum Controls {
forward = 'forward', …
```

feat: add types to keyboard controls

---

README.md

duplicate variable, and missing parenthesis

fixed typo in ScrollControls README

---

README.md

docs: correct spelling of <torusKnotGeometry /> in README

---

src/core/CatmullRomLine.tsx
src/core/CubicBezierLine.tsx
src/core/QuadraticBezierLine.tsx

Prefers to import `Line2` from `three-stdlib` rather than `three/examples`.

fix: don't import from three/examples

---

README.md

Signed-off-by: Pierre-Louis Delcroix <pierrelouisdelcroix2001@gmail.com>
The brackets are missing in the README in the example of `KeyboardControls`.
Currently the map is declared as a single entry. The brackets are needed in order to declare the map as an array of `KeyboardControlsEntry`. 
I added the brackets in order to declare the map as an array of KeyboardControlsEntry
- [ x ] Documentation updated

fix: missing brackets added to the KeyboardControls example

---

README.md
src/core/useVideoTexture.tsx

`canplay` and `canplaythrough` is not fired on iOS device, after hook is called.
This [StackOverflow](https://stackoverflow.com/questions/50051639/javascript-html5-video-event-canplay-not-firing-on-safari) says "loadedmetadata" is better on iOS (11.3.1) device. 
And on my iOS 16.1.1 device, looks the same.
allow `loadedmetadata` trigger.
- [] Ready to be merged

fix: add type to VideoTextureProps

---

src/web/pivotControls/index.tsx

`PivotControls` accept a `annotationClass` prop, but the component does not actually place this into the `PivotContext`. This results in styles for the `PivotControls` label / annotation not being applied. This PR fixes that.
- Custom styles for label don't work, while the prop is documented.
- Actually used the prop in the `PivotControls` component by adding it to the context that is created for the control (it was already present in the type definition).

fix: put PivotControls annotation class prop in PivotContext

---

src/core/Instances.tsx

The Instance component wasn't using the side of the parent material for its raycast.
Added the side of the material before raycating.

fix(Instances): use parent raycast side

---

README.md
src/web/View.tsx

Resolves #944 
Since the [upstream fix to @react-three/fiber](https://github.com/pmndrs/react-three-fiber/pull/2339) has been released in v8.1.0, this takes advantage of the position information to get `View` working as expected in non-fullscreen use cases.
Additionally, a warning is logged (using console.warn) if an older version of react-three-fiber is detected. I couldn't find any existing logging infrastructure for this type of dev mode warning at a glance so I opted to keep it simple. Please advise if there is a better approach here.

fix: View component supports non-full screen use cases

---

.storybook/stories/useTrailTexture.stories.tsx
README.md
src/core/index.ts
src/core/useTrailTexture.tsx

New hook that can be used to generate a texture with a pointer trail. Useful for controlling interactive displacement etc in shaders.
https://user-images.githubusercontent.com/420472/203173825-b83bdef4-9191-4199-9986-51ff48826254.mp4

feat: add useTrailTexture + story

---

src/core/Bounds.tsx

The `to` method of `useBounds` hook is not exported.
Updated the `BoundsApi` type to include the `to` method.
- [X ] Ready to be merged

fix: method to of BoundsApi is not exported

---

.storybook/stories/ScreenSpace.stories.tsx
README.md
src/core/ScreenSpace.tsx
src/core/index.ts

New abstraction that removes camera position and rotation to children.
Gives ability to have 3d objects in the HUD of the camera.
Added /src/core/ScreenSpace.tsx
Added info to readme.md
Added to src/core/index.ts
Added .storybook/stories/ScreenSpace.stories.tsx

feat: ScreenSpace

---

src/core/useVideoTexture.tsx

Currently we're using `useVideoTexture` in our application, but when I was trying to control the `start` property on my end, it was not working because the array of dependencies was missing the `start` property. I don't know if it's the right approach to control the behavior of the start property like this, if it's not, just let me know. You can find the sample below (I'll probably change this code, because it's seems redundant, but just so you can understand the scenario):
```
export const VideoMaterial = ({ url }) => {
const canPlay = useAudioPlayStore((state) => state.canPlay);
const [start, setStart] = useState(false);
const texture = useVideoTexture(url, {
playsInline: true,
start,
});
useEffect(() => {
if (canPlay) setStart(true);
}, [canPlay]);
return <meshBasicMaterial …
```

fix: missing dependency in useVideoTexture

---

src/core/TransformControls.tsx

Events function were returned in useLayoutEffect which caused them to be called on unmount etc
added void in front

fix: remove TransformControls events from cleanup

---

src/materials/MeshRefractionMaterial.tsx

I encountered this problem while trying to use MeshRefractionMaterial directly via JS (see my journey here: https://github.com/pmndrs/drei/issues/1181).  Without this fix, the fresnel calculation is sometimes wrong and can result in black holes on models with this material.
Normalize vNormal in the vertex shader.

fix(MeshRefractionMaterial): vNormal should be normalized

---

src/core/useAnimations.tsx

resolves #1175 
Added useEffect to stop actions when the mixer changes.
[ x ] Documentation updated
[ x ] Storybook entry added
[ x ] Ready to be merged
Not sure, if this is ready to be merged tbh. but it fixes my bug at least... But it might have second-order consequences that I am not aware of / think of since I am quite new to the whole drei/r3f/three.js ecosystem.

Stop all AnimationActions on unmount/mixer change

---

.storybook/stories/Grid.stories.tsx
README.md
src/core/Grid.tsx
src/core/index.ts
yarn.lock

Port of https://github.com/threlte/threlte/blob/main/packages/extras/src/lib/components/Grid/Grid.svelte by @grischaerbe
btw @grischaerbe i noticed the original is missing tonemapping and encoding fragments, the colors weren't managed. i'm also not 100% sure but i removed axes because i think it can just be rotated via `mesh.rotation`. at work we have a grid component that has distance attenuation, similar to how grids work in CAD. i will ask colleagues if they can add, that would be a super useful addition imo.

feat: grid

---

src/core/Text.tsx

The underlying troika-text-three instance uses the following as options for the 'whitespace' property:
- 'normal'
- 'nowrap'
Where 'normal' indicates that the 'overflowWrap' property should be enforced, and 'nowrap' indicates that no wrapping should occur.
resolves #1199 
This commit adds the missing 'nowrap' option to the existing prop types. Note that the extraneous 'overflowWrap' option -- while unused under the hood -- is remaining such that no breaking changes are introduced.
Unsure if storybooks need updated -- please advise if so.

fix(Text): add missing whitespace option to types

---

.storybook/stories/ScrollControls.stories.tsx
src/web/ScrollControls.tsx

Canvas with ScrollControls nested deeply in html dom do not respect offsets applied to ancestors.  
Instead of rellying on `offsetLeft` and `offsetTop` of `gl.domElement.parentNode` we need to compute actual position and offset of `parentNode` in attempt to modify logic of raycaster 
Updated example of ScrollControls with update materials wireframe property on hover model:
https://codesandbox.io/s/scrollcontrols-gltf-forked-0wsrfc?file=/src/App.js
If we will add margin to wrapper div element hover logic do not work correct because do not respect `div` margin 
https://codesandbox.io/s/scrollcontrols-gltf-forked-q6nuxk?file=/src/App.js
the same problem could be reproduced in `Controls/ScrollControls` `Inside a container` storybook example 
before fix: …

fix(ScrollControls): fix offset computation for raycaster

---

README.md

There was unnecessary semicolon before opening tag of ScrollControls [here](https://github.com/pmndrs/drei#scrollcontrols) at code section

Removed unnecessary semicolon

---

src/core/OrbitControls.tsx

The type of OrbitControl's change event target was `EventTarget | null`, which isn't accurate or is the best type possible.
It isn't accurate because to the event be fired the OrbitControls needs to be instantiated in a Canvas with a camera, so it'll never be `null`, but `EventTarget` isn't the best type either, because this event target always have an `object` property containing the respective camera, so a better type for the change event target is `EventTarget & { object: Camera }`.
This fixes the problem above by creating a new type `OrbitControlsChangeEvent` with the correct `target` type

fix: improve OrbitControls change event type

---

README.md
src/core/Line.tsx

Line currently only renders a ThreeJS Line2. There is no support for LineSegments2.
Adds a segments prop to allow switching between ThreeJS Line2 and LineSegments2

feat(Line): support for LineSegments2

---

README.md
package.json
src/core/CameraControls.tsx
yarn.lock

Now that [camera-controls](https://github.com/yomotsu/camera-controls/releases/tag/v1.38.0) lib implements `connect`/`disconnect` methods, I'm following [@drcmda recommendation](https://github.com/yomotsu/camera-controls/issues/262#issuecomment-1399431569) and update the `CameraControls` drei component to take advantage on

fix(CameraControls): taking advantage on new released `.connect` method

---

src/core/MeshTransmissionMaterial.tsx

First OSS participation bare with me :) 
no issue was open for this decided to jump on it 
https://github.com/pmndrs/drei#meshtransmissionmaterial , background property type is only Three.Texture where the comments state it can use a color
Added color type to background property
Tested on an active project works as intended when adding Three.color type

fix: adds color type to background meshtransmissionmaterial

---

package.json
yarn.lock

`camera-controls` has just [turned 2](https://github.com/yomotsu/camera-controls/releases/tag/v2.0.0)! Just updating the dependency to this latest version.

`camera-controls` v2

---

README.md
src/core/CameraControls.tsx

Adding the `makeDefault` prop to `CameraControls`, in order to:
```tsx
const controls = useThree(state => state.controls)
```
like explained in the doc:
https://github.com/pmndrs/drei/blob/3b894e83a97d08e8bb25655c971c5dc93738b630/README.md?plain=1#L339

CameraControls[makeDefault]

---

.storybook/stories/PresentationControls.stories.tsx
README.md
package.json
src/web/PresentationControls.tsx
yarn.lock

Fixes: https://github.com/pmndrs/drei/pull/1239#issuecomment-1407586486
This PR alignes `<PresentationControls />` target dom element to that similar to `<OrbitContorls />`. Now by default `PresentationControls ` will attach to `events.connected`. This makes it so that it is attached to the top-most parent element of the Canvas and all `<Html />`, making it work regrdless of the zIndex of the Canvas relative to the `<Html />`
A `domElement` prop is also added to let uses select their own target element.
Unfortunately, it seems like latest `@use-gesture/react` [is broken on CodeSandbox](https://github.com/pmndrs/use-gesture/pull/560#issuecomment-1365949123), so you'll have to download and run [this CodeSandbox](https://codesandbox.io/s/tender-sun-pxggh0?file=/src/Experience.js)

fix: Presentation controls target element

---

README.md
src/core/CameraControls.tsx

`onChange` now reacts to `"update"` CC event.
see https://github.com/pmndrs/drei/issues/1254

Cameracontrols[onChange] - "update" CC event

---

src/core/MeshTransmissionMaterial.tsx

I realized my `roughnessMap` wasn't being applied properly, zones where roughness should be near 0, were near 1 (with a roughness uniform of 1).
I checked the code and seems like the `roughnessFactor` wasn't being used for light calculations, so I changed it where the `roughness` uniform was being directly used and the issue seems to be fixed.
- With current drei's version: https://codesandbox.io/s/quizzical-pine-p6049t
- With this PR's version: https://codesandbox.io/s/blissful-flower-s15lj1

fix: (MeshTransmissionMaterial) Use roughnessFactor instead of roughness

---

.storybook/preview.ts
.storybook/preview.tsx
.storybook/stories/Billboard.stories.tsx
.storybook/stories/CameraShake.stories.tsx
.storybook/stories/Environment.stories.tsx
.storybook/stories/GizmoHelper.stories.tsx
.storybook/stories/Image.stories.tsx
.storybook/stories/Svg.stories.tsx

A couple of storybooks were broken because of a bug from Storybook itself. 
List of broken storybooks that this PR fixes:
- https://drei.pmnd.rs/?path=/story/staging-camerashake--camera-shake-story
- https://drei.pmnd.rs/?path=/story/staging-camerashake--camera-shake-with-orbit-controls-story
- https://drei.pmnd.rs/?path=/story/abstractions-billboard--billboard-text-story
- https://drei.pmnd.rs/?path=/story/staging-environment--environment-story
- https://drei.pmnd.rs/?path=/story/staging-environment--environment-files-story
- https://drei.pmnd.rs/?path=/story/staging-environment--environment-ground-story
- https://drei.pmnd.rs/?path=/story/abstractions-image--image-story
- https://drei.pmnd.rs/?path=/story/gizmos-gizmohelper--gizmo-helper-story
- …

fix: multiple stories because of Storybook bug

---

src/core/useGLTF.tsx

Use the latest Draco version
https://github.com/google/draco/releases/tag/1.5.5

Update Draco decoders path

---

.storybook/stories/KeyboardControls.stories.tsx
src/web/KeyboardControls.tsx

Passing an `onChange` callback to `KeyboardControls` triggers a Rules of Hooks error when a key is pressed. 
See screenshot:
In `src/web/KeyboardControls.tsx`, the `onChange` callback tries to get the state of the pressed keys by calling [`api[2]`](https://github.com/pmndrs/drei/pull/1279/files#diff-3467df2300c36a8dccc0baacef385fdfa050d22b32a918e1661e7b018cf54e29R63), which is a reference to `useControls`. It looks like that should be `api[1]`, which is a reference to `useControls.getState` and can safely be called at keypress time.
So this PR fixes that, and adds an example of an `onChange` handler to the Storybook story to test that by changing the color of the Player when the user clicks Space.
See screenshot
Also just wanted to say thanks for this library! This and R3F have made …

fix: don't call a hook in onChange for KeyboardControls

---

src/web/Html.tsx

The zIndex of the canvas for `occlusion="blending"` will have to be alterted for the effect to work but no need to do that for legacy occlusion

fix: Restore HTML raycast zIndex

---

src/core/Billboard.tsx

In my scene the camera is nested inside an animated group. The Billboard component only takes the local camera quaternion into account, so as soon as a parent object rotation comes into play, the Billboard effect breaks.  
Inset of copying the local rotation of camera.quaternion, I suggest using camera.[getWorldQuaternion()](https://threejs.org/docs/#api/en/core/Object3D.getWorldQuaternion).

Billboard: use camera world rotation

---

src/core/GizmoHelper.tsx

This change resolves an issue when using the GizmoHelper with a non-standard "up" vector for your world (e.g. +Z up rather than the default +Y). By setting the up vector when computing each tweened rotation for the animation, the world up can be presevered and avoid the flicker to set the camera position up after the animation completes. 
To demo this change, create a scene with a camera that has `up={[0, 0, 1]}` using a gizmo to view the behaviour where the view "snaps" to it's final position and does not obey the up vector during the animation. 
While this resolves this issue, the `GizmoViewport` will still be presented in the default world orientation (i.e. with +Y up) which should be addressed in a separate PR. 
Relates to #522 
When computing the quaternion rotation to apply, the …

fix: ensure `<GizmoHelper />` rotations respsect camera up direction

---

README.md

Just pointing the Discord link in the README direclty to `#drei` channel

link to Discord `#drei` channel

---

README.md

Just adding a direct link to the Codespace in the README:
[![Open in GitHub Codespaces](https://img.shields.io/static/v1?&message=Open%20in%20%20Codespaces&style=flat&colorA=000000&colorB=000000&label=GitHub&logo=github&logoColor=ffffff)](https://github.com/codespaces/new?template_repository=pmndrs%2Fdrei)

Codespace badge

---

src/core/RoundedBox.tsx

fix: don't import example subpaths for compat

---

README.md

https://codesandbox.io/s/2cemck?file=/src/App.js

docs(useVideoTexture): adding a csb example to the README

---

src/web/View.tsx

On nextjs when navigating View sometimes lose events, the component was missing some dependency array in some hooks.
Related:
https://github.com/pmndrs/react-three-next/pull/117

fix: wrong dependency array on View

---

src/core/Decal.tsx

Resolves #1365 by implementing `React.forwardRef` and exporting `DecalProps`.

feat(Decal): ref prop, export types

---

.storybook/stories/useCubeCamera.stories.tsx
README.md
src/core/CubeCamera.tsx
src/core/index.ts
src/core/useCubeCamera.tsx

New hook `useCubeCamera()` "low-level" version:
```tsx
const { fbo, update, camera } = useCubeCamera({resolution?, near?, far?, fog?, envMap?})
useFrame(() => {
// camera.position.set(...) // (1) position the cube-camera wherever you want
ref.current.visible = false
update() // 📸
ref.current.visible = true
})
<group {...props}>
<primitive object={camera} /> {/* add to the scene or (1) */}
<mesh ref={ref}>
<sphereGeometry args={[5, 64, 64]} />
<meshStandardMaterial roughness={0} metalness={1} envMap={fbo.texture} />
</mesh>
</group>
```
Classic component `<CubeCamera>` version (uses hook internally):
```tsx
<CubeCamera {...props}>
{(texture) => (
<mesh>
<sphereGeometry args={[5, 64, 64]} />
<meshStandardMaterial roughness={0} metalness={1} envMap={texture} />
</mesh>
)}
</CubeCamera>
```

feat: `useCubeCamera` hook

---

src/core/CameraControls.tsx

Camera controls won't work with ondemand frame loop
Added the event listeners on [camera controls docs](https://github.com/yomotsu/camera-controls#events) for transitions to work on demand frame loop

Add camera controls transition event listeners

---

src/core/Text.tsx

Add missing field "sdfGlyphSize" on Text props type definition.
closes issue #1339

fix: add sdfGlyphSize on Text

---

.storybook/stories/Resize.stories.tsx
README.md
src/core/Resize.tsx
src/core/index.ts

A `<Resize>` component that rescales children **to `1`** (highest dimension by default).
-> We can then re`scale` differents things relatively, even for example if they were scaled differently in blender:
```jsx
const house = useGLTF("/house.gltf");
const character = useGLTF("/character.gltf");
<Resize scale={0.7}><primitive object={house.nodes.table} /></Resize>    {/* 70cm table */}
<Resize scale={1.8}><primitive object={character.nodes.john} /></Resize> {/* 1.8m guy */}
```

feat(Resize): new component

---

README.md
src/core/AccumulativeShadows.tsx
src/core/Cloud.tsx
src/core/ContactShadows.tsx
src/core/Effects.tsx
src/core/GizmoViewcube.tsx
src/core/GizmoViewport.tsx
src/core/GradientTexture.tsx
src/core/Image.tsx
src/core/MeshReflectorMaterial.tsx
src/core/Reflector.tsx
src/core/useCubeCamera.tsx
src/core/useFBO.tsx
src/core/useVideoTexture.tsx
src/materials/BlurPass.tsx

Mirrors https://github.com/pmndrs/react-three-fiber/pull/2829, adding a preference for `colorSpace` over `encoding`. The latter is handled internally by R3F for color textures, and should only be set on `UnsignedByteType` render targets, where I've opted to use `HalfFloatType` here instead.

fix: prefer colorspace/encoding, don't encode fp16+

---

src/core/Points.tsx

There are two issues:
1. `_position` is the world position. In the original code, _position is retrieved from the bufferattribute which is local position
2. the matrix that is applied in the original code is the parent matrixWorld. This is also in line with the line 58.

Fix points raycast

---

src/core/useAnimations.tsx

Fix #1379
This PR fixes error `Cannot redefine property` when using `useAnimations` with duplicated animation's name in 3Dmodel
Example `duplicated animation's name` file is exported from [threejs-editor](https://threejs.org/editor/): 
[scene.zip](https://github.com/pmndrs/drei/files/11218238/scene.zip)
Solution can be found here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_redefine_property

fix(useAnimations): error 'cannot redefine property' will occur if animationclip.name is duplicated

---

src/core/MeshRefractionMaterial.tsx

Ensures `MeshRefractionMaterial` is reusable between unique meshes. Before, it was order dependent.
https://codesandbox.io/s/k6uiie
| Torus Last | Diamond Last |
|--------|----|
| ![image](https://github.com/pmndrs/drei/assets/23324155/ed519ff4-eb3e-44dd-ba90-ab1a60f99998) | ![image](https://github.com/pmndrs/drei/assets/23324155/76a98976-fcf5-4823-bfc1-a3390572acad) |

fix(MeshRefractionMaterial): work across unique meshes

---

package.json
yarn.lock

Fixes #1449
Includes recent fixes for three.js and react-native compatibility. This is already fixed with a clean install, but a bump will ensure CI will notice this update.

fix: upgrade deps

---

src/core/Grid.tsx

Fixes #1451 (not `expo-gl` specific)
```diff
-uniform float infiniteGrid;
-uniform float followCamera;
+uniform bool infiniteGrid;
+uniform bool followCamera;
-vec3 pos = position.xzy * (1. + fadeDistance * infiniteGrid);
-pos.xz += (cameraPosition.xz * followCamera);
-worldPosition = pos;
+worldPosition = position.xzy;
+if (infiniteGrid) worldPosition *= 1.0 + fadeDistance;
+if (followCamera) worldPosition.xz +=cameraPosition.xz;
```

fix(Grid): use bool glsl type

---

src/web/PresentationControls.tsx

Fixes #1446
 I ran into a bug where when I disable the PresentationControls it continues to override the cursor="pointer" behavior I had set on the object.
This change moves the PresentationControls cursor cleanup effect code into the if statement so that it will avoid overriding any cursor behavior set when PresentationControls is disabled.

fix(PresentationControls): cursor effect bug prevents any default cursor behaviors

---

README.md
src/core/SpriteAnimator.tsx

Added a Sprite animator component that is extends the default Three Sprite to allow the playback of sprite-sheets, either image only ones or JSON-Array / JSON-Hash ones. https://gamedev.stackexchange.com/a/116000
Created a component that enhances the default Three Sprite element by parsing the texture image and/or the accompanied JSON file in order to create a series of standalone frames. Those frames are used as a cutoff texture on the Sprite which they progress through useFrame and thus creating the animation.
By using JSON enhanced spritesheets the user can include multiple animations (e.g. Idle, Walk, Run) on the same spritesheet, and control which one is the component currently playing. The playback can change on runtime so it is possible to create a whole character animation set …

feat: add sprite animator component

---

README.md
src/core/SpriteAnimator.tsx
src/core/index.ts

Fix for #1464 
Export issue for TS, documentation issue with navigation
- Added `toneMapped=false` to preserve the sprite texture colors
- Added a proper anchor tag for the ReadMe section
- Added proper export in the `index.ts` file for SpriteAnimator
- [ x] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))

fix: for #1464 (added tonemapped=false, fix for readme link, proper export)

---

package.json
rollup.config.js

Mirrors https://github.com/pmndrs/react-three-fiber/pull/2749 where the previous Babel configuration didn't correctly down-level transpile. Ideally, we'd use Vite/ESBuild where we can specify an ES version.

fix: transpile class properties

---

README.md
src/core/SpriteAnimator.tsx

fix(SpriteAnimator): simplified aspect ratio calculation and fixed bu…
Improved documentation
Simplified aspect ratio calculation
- Added missing properties from ReadMe
- Simplified the aspect-ratio calculation for the sprites and fixed a bug  when re-rendering the Sprite while having zoomed-in/out with orbitcontrols
- [x ] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
- [x ] Ready to be merged

fix(SpriteAnimator): simplified aspect ratio calculation

---

src/core/OrbitControls.tsx

Enables use of key events with `listenToKeyEvents` to target the default element, or accepts an HTML element to target.
```jsx
<OrbitControls keyEvents ={boolean | HTMLElement} />
```

feat(OrbitControls): keyEvents prop

---

src/core/MeshTransmissionMaterial.tsx

Fixes #1482 where new `USE_ANISOTROPY` chunks break with the custom `anisotropy` prop (now reserved) and adds back the prop removed in 549493df2693828b152b0bc4edf45c3571421146.

fix(MeshTransmissionMaterial): unset USE_ANISOTROPY, add compat alias

---

src/core/MeshTransmissionMaterial.tsx

#1483 added props in the wrong order. This makes them explicit.

fix(MeshTransmissionMaterial): explicit order

---

src/core/Facemesh.tsx
src/materials/WireframeMaterial.tsx

Cleans up some circular dependencies which can break stricter bundler configs.

fix: dedup circular dependencies

---

src/core/Facemesh.tsx

Uses `THREE.MathUtils` rather than importing from `three/src` via a wildcard subpath. This can break resolution in ESM resolvers which require explicit file extensions or be stripped to do the same -- https://github.com/mrdoob/three.js/issues/24593.

fix(Facemesh): don't import from src

---

src/core/FaceLandmarker.tsx

In the meantime of https://github.com/pmndrs/drei/pull/1510 (that aims at automating this), this PR manually aligns the `FaceLandmarkerDefaults.basePath` to current `@mediapipe/tasks-vision` package version: `0.10.2-rc2`

fix: FaceLandmarkerDefaults.basePath aligned with 0.10.2-rc2 version

---

README.md

Added a note to describe how to prefetch the draco binaries from the google CDN, as requested by Paul

docs: Added note for prefetching draco binaries from CDN

---

src/core/Caustics.tsx

41 instances of `new Vector3` and `.clone()` were being used inside useFrame 
Made re usable array of vector3s and changed all instances of new/clone to set/copy
update test sandbox https://codesandbox.io/s/sandbox-caustics-vector3-update-6mkhxl?file=/src/CausticsUpdate.tsx (red is old green is updated caustics)
Cody Suggested adding `/* @__PURE__ */` to all the vector3 for memoization
Paul suggested not adding it in favor of this commit(which automates this task) getting merged one day https://github.com/pmndrs/drei/pull/1479

fix: remove use of new/clone Vector3 in useFrame

---

src/core/CubeCamera.tsx

Resolves #1513.
CubeCamera has wrong types. Referring to: 
https://discourse.threejs.org/t/react-three-fiber-type-texture-texture-element-is-not-assignable-to-type-reactnode-tex-texture-reactnode-error/43554/3

fix: :label: types of CubeCamera

---

src/core/SpriteAnimator.tsx

The current `SpriteAnimator` doesn't flip the sprite upon a `flipX` change. 
This PR fixes the `flipX` property on the `SpriteAnimator`. The property now only works to what you set it initially and doesn't update via a state change. It adds the `flipX` variable as a dependency to the `useEffect` that runs `modifySpritePosition`. This `modifySpritePosition` util function makes it so the sprite is correctly flipped on a state change. 
I've cloned the `SpriteAnimator` codesandbox and added the `flipX` property to the useEffect:
https://codesandbox.io/s/r3f-sprite-animator-v2-0-wip-forked-wqslq5?file=/src/SpriteAnimator.tsx:3969-3974
It now works as expected.

fix: recalculate sprite position on x axis flipping

---

src/web/ScrollControls.tsx

In drei project, it generally uses `React.CSSProperties` instead of StyleHTMLAttributes<any>
So, i fix style type of ScrollHtml for type consistency.

fix: style type of ScrollHtml

---

src/core/Grid.tsx

Grid positioning and fade are not calculated correctly for arbitrary transformations.
Related issue: [1366](https://github.com/pmndrs/drei/issues/1366)
Changed the shader code and added an effect which feeds the current grid plane position and projected camera position onto it to fix this

fix: correct grid fade and positioning for arbitrary transform

---

src/core/Caustics.tsx

THREE Colorspace warnings when using `drei/caustics` as `encoding` is mentioned as renderTarget/fbo settings
Removed encoding as it's already Linear by default and removed RGBAFormat (also default)
which should make it compatible with old as well as new three color management 
sandbox comparing the both
https://codesandbox.io/s/caustics-fbo-setting-updated-g87c2p?file=/src/App.js

fix: Caustics remove deprecated fbo encoding & format

---

.storybook/stories/ContactShadows.stories.tsx
src/core/ContactShadows.tsx

closes issue #391
There was no way to set positive Y position in `ContactShadows` as the position of the internal `OrthographicCamera` wasn't compensating the distance of the shadow's position.
This fix resolves issue #391.
The solution is to use the value of incoming position Y property (if defined) and set that on the Z position of the `OrthographicCamera`.

fix: enable positive Y positioning in ContactShadows

---

.github/workflows/release.yml
package.json
release.config.js
yarn.lock

- using local devDependencies `semantic-release` package (rather than 3rd-party `cycjimmy/semantic-release-action`)
- simplifying the workflow: only 1 job now

semantic-release optims

---

src/core/ContactShadows.tsx

Implements #391 by adding a `near` prop to customize the range of the camera's clipping planes.

feat(ContactShadows): near prop

---

.github/workflows/release.yml
release.config.js

`canary-*` -> `@react-three/drei@x.y.z-canary-*.X`
Eg:
- create a `canary-*` branch, eg this one: `canary-branches`
- push your `fix:` commit to it
- enjoy a [`@react-three/drei@9.77.11-canary-branches.1`](https://www.npmjs.com/package/@react-three/drei/v/9.77.11-canary-branches.1) on the `canary` channel
Tested on this CSB: https://codesandbox.io/s/cyf753

`canary-*`

---

.eslintignore
.gitignore
test/e2e/e2e.sh
test/e2e/snapshot.test.js

some optims:
- npm create in /tmp
- waitForServer to be up

e2e optims

---

src/core/Grid.tsx

Class instances being created inside useFrame 
Create it outside useFrame and reuse it
sandbox testing the update https://codesandbox.io/s/grid-component-update-4dw7vh?file=/src/GridUpdate.tsx

fix: grid , reuse useFrame assets

---

.storybook/stories/StatsGl.stories.tsx
README.md
package.json
src/core/StatsGl.tsx
src/core/index.ts
yarn.lock

Created a new tool based on stats.js more accurate and precise for WebGL experiences:
https://github.com/RenaudRohlinger/stats-gl
This component introduces a `<StatsGl />` that makes it available more easily based on the same logic as `<Stats />`

feat: new stats tool

---

src/core/Sparkles.tsx

Fixes an issue where specifying any array of values causes Sparkles to recreate itself on render.

fix(Sparkles): diff scale prop

---

src/core/MeshTransmissionMaterial.tsx

In drei/MeshtransmissionMaterial 
in this section https://github.com/pmndrs/drei/blob/9edcade6e4cb3aba2ed11ff5432cfcae76189548/src/core/MeshTransmissionMaterial.tsx#L416-L436
if backside is off , mtm is not restored on the "parent" mesh
so in the next lines thickness, side, and buffer are actually being set on the discard material instead of mtm
Moving `parent.material = ref.current` before the value is set
This error does not affect r3f somehow

fix: MeshTransmissionMaterial prevent setting values on discard mat when backside is off

---

README.md
src/web/useCursor.tsx

If you are setting cursor styles in any Canvas parent other than body, they will take precedence over the styling in the body.
Allow `useCursor` to receive a forth optional parameter to specify where to set the cursor style. It defaults to `document.body`.

feat: useCursor accepts custom HTML element

---

src/web/PresentationControls.tsx

The current types fail with strict package managers since it imports from `@react-spring/core` which is not a direct dependency of `@react-three/drei`.
```
ERROR in ./node_modules/@react-three/drei/web/PresentationControls.d.ts:2:30
TS2307: Cannot find module '@react-spring/core' or its corresponding type declarations.
1 | import * as React from 'react';
> 2 | import { SpringConfig } from '@react-spring/core';
|                              ^^^^^^^^^^^^^^^^^^^^
3 | export declare type PresentationControlProps = {
4 |     snap?: Boolean | SpringConfig;
5 |     global?: boolean;
```
Import `SpringConfig` from `@react-spring/three` instead of `@react-spring/core` to fix the error.

fix: import SpringConfig from @react-spring/three

---

src/core/useEnvironment.tsx

The useEnviroment hook cannot parse a url that has query parameters in it even if the url itself leads to a file with a valid extension. 
Changed the extension variable in useEnvironment to split at questions marks and get the first of the array, which should be the extension in the case query parameters were used

fix: changed extension in useEnvironment to address query params

---

src/core/AccumulativeShadows.tsx
src/core/Caustics.tsx
src/core/Grid.tsx
src/core/Image.tsx
src/core/MeshPortalMaterial.tsx
src/core/PointMaterial.tsx
src/core/Sparkles.tsx
src/core/Stars.tsx
src/materials/ConvolutionMaterial.tsx
src/materials/MeshRefractionMaterial.tsx
src/materials/SpotLightMaterial.tsx

Adds compat for r154 shader chunk renames of https://github.com/mrdoob/three.js/pull/26206 and https://github.com/mrdoob/three.js/pull/26278.

fix: compat for r154 shader chunk renames

---

src/core/useAnimations.tsx

Previously `actualRef` did not update if a new `root` argument was passed. Additionally, the `clips`, `names`, and `actions` of the API did not update if a new `clips` argument was passed.
Resolves #1481, resolves #1548.
Correctly update the API and ref in appropriate effects.

fix(useAnimations): ensure API result updates with `clips` and `root`

---

src/core/useAnimations.tsx

Previously, `mixer.stopAllAction` was called when `mixer` changed. This behavior was undesirable because
1. The `mixer` reference was stable and never changed
2. This would occur after uncaching the actions and could lead to undefined behavior
Move the `mixer.stopAllAction` call to the cleanup function when `clips` changes.

fix(useAnimations): correctly stop all actions when clips change

---

src/core/Example.tsx

Found I was having this type error in my node_modules when running type check in my project.
This looks to be due to an incorrect syntax when importing this type, although I might be unaware of a newer TS feature.
```
node_modules/@react-three/drei/core/Example.d.ts:2:15 - error TS1005: ',' expected.
2 import { type Color } from '@react-three/fiber';
```
Changed to `import type { Color } from '@react-three/fiber';`

fix: type error in `core/Example.tsx`

---

src/core/ScreenQuad.tsx

Closes #1578
ScreenQuad outputs this error with recent ThreeJS versions (eg: r155) :
> THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.
Workaround to avoid the computation of `boundingSphere` at render time.

fix(ScreenQuad): init bounding sphere

---

src/core/useAnimations.tsx

In #1593 I overlooked the fact that instead of passing a `root` to `useAnimations`, the user can attach the returned `actualRef` to a component. This resulted in #1617 and 60b92ed40cfdd6b6fe238742215acd8a82783921.
Resolves #1617.
The fix is to check that `root` is defined before assigning it to `actualRef.current`. I also removed the dependency list from this effect because it should run every render in case `actualRef.current` changes (or `root.current` changes if a ref object is passed for `root`).

fix(useAnimations): support attaching returned ref to component and restore prior fixes

---

src/web/Html.tsx

The `occlude={[ref]}` prop is broken and not working in the current drei storybook example.
Reordered the if checks for the property to use the more specific check first, then the more generic inequality check second
Fix makes the documentation accurate, existing Storybook example work

fix: Html occlude with ref, logic correction

---

src/core/AccumulativeShadows.tsx

resolves #1611 
ProgressiveLightMap is not being rendered correctly because the wrong texture format being used on iPadOS with Safari.
Currently the code checks the user agent to determine what float type to use (half float or float). When the user agent is being spoofed, texture is not rendered correctly (this happens by default on iPadOS with Safari). 
To use [THREE.FloatType ](https://threejs.org/docs/#api/en/textures/DataTexture) the browser must support the 	OES_texture_float and OES_texture_half_float WebGL extension. 
I added a check for those extensions to determine what float type to use.

fix(AccumulativeShadows): set progressivelightmap Texture to halffloattype and nearestfilter

---

src/core/SpriteAnimator.tsx

The `<SpriteAnimator />` component currently doesn't stop playing even if the `loop` prop is set to false.
This is due to the component not keeping track if the last frame has been displayed. It currenly only calls the callback `onEnd`. https://github.com/pmndrs/drei/issues/1497
To fix this I've added a `hasEnded` ref to track if the animation has ended.
The value of `hasEnded` is reset to `false` if the prop `frameName` changes.

fix(SpriteAnimator): add hasEnded ref to prevent infinite looping

---

README.md
package.json
src/core/useGLTF.tsx
yarn.lock

This issue https://github.com/pmndrs/drei/issues/1597 asked for a way to define Draco decoder path globally.
I added a `useGLTF` method called `setDecoderPath(path)` that updates a `decoderPath` variable, the default one  remains gstatic servers

set useGLTF draco decoder path globally

---

src/core/BBAnchor.tsx

Error at Vector3 type anchor .
Fixed Vector3 type anchor prop to work.
`[...anchor][0]` is better solution than `Array.isArray(anchor) ? anchor[0] : anchor.x`, but Types not supporting of Vector3 iterator.

fix(BBAnchor): fixed Vector3 type anchor to work

---

README.md
src/core/SpriteAnimator.tsx

Added feature to support PlaneGeometry in addition to SpriteGeometry for SpriteAnimator. This will allow the spritesheet to be rotated and moved with its parent or group if it doesn't need to be always facing the camera. Displaying on a SpriteGeometry only had certain limitations, especially around transformations.
Added optional property `asSprite` to control whether or not the sprite texture renders on a Plane or a Sprite geometry.  The default value is `asSprite = true` so it doesn't break current implementations.
- [ x] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))

feat: added optional Sprite or Plane geometry for SpriteAnimator

---

src/web/Select.tsx

Using drei with `@types/three@0.156.0` produces a type error because of the [change in meaning to the generic parameter for `Object3D`](https://github.com/three-types/three-ts-types/releases/tag/r156):
```
ERROR in node_modules/@react-three/drei/web/Select.d.ts:13:53
TS2344: Type 'Event<string, unknown>' does not satisfy the constraint 'Object3DEventMap'.
Type 'Event<string, unknown>' is missing the following properties from type 'Object3DEventMap': added, removed
11 | };
12 | export declare function Select({ box, multiple, children, onChange, onChangePointerUp, border, backgroundColor, filter: customFilter, ...props }: Props): JSX.Element;
> 13 | export declare function useSelect(): THREE.Object3D<THREE.Event>[];
|                                                     ^^^^^^^^^^^
14 | …
```

fix: type error with @types/three@0.156.0

---

README.md

I did not find a github issue for this. This fixes an apparent typo in the README.
Fix the typo. In docs, pictured below, it should say "same API as PerspectiveCamera."
At least, that is how it seems.

docs: fix typo, reference the correct/relevant component

---

rollup.config.js
src/core/AccumulativeShadows.tsx
src/core/Caustics.tsx
src/core/Facemesh.tsx
src/core/Grid.tsx
src/core/Image.tsx
src/core/Instances.tsx
src/core/MeshPortalMaterial.tsx
src/core/Outlines.tsx
src/core/PointMaterial.tsx
src/core/Points.tsx
src/core/Sparkles.tsx
src/core/SpriteAnimator.tsx
src/core/Stars.tsx
src/helpers/constants.ts
src/materials/ConvolutionMaterial.tsx
src/materials/MeshRefractionMaterial.tsx
src/materials/SpotLightMaterial.tsx
src/web/KeyboardControls.tsx
src/web/useCursor.tsx

Fixes #1676.
Reverts #1661 which seems to break some uses of `extend`.

fix: revert build-time annotations

---

package.json
yarn.lock

fix(OrbitControls): don't use pointer capture

---

README.md

~~castShadows~~ -> castShadow 
https://github.com/pmndrs/drei#stage
- [X ] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
- [X ] Ready to be merged

docs: fix spelling of castShadow in Stage/README

---

src/core/MotionPathControls.tsx

The current types cause errors for `@types/three@0.156.0` and above because the `Object3D` generic is [no longer just an event type](https://github.com/three-types/three-ts-types/releases/tag/r156):
```
Error: node_modules/@react-three/drei/core/MotionPathControls.d.ts(6,50): error TS2344: Type 'Event<string, unknown>' does not satisfy the constraint 'Object3DEventMap'.
Type 'Event<string, unknown>' is missing the following properties from type 'Object3DEventMap': added, removed
Error: node_modules/@react-three/drei/core/MotionPathControls.d.ts(7,51): error TS2344: Type 'Event<string, unknown>' does not satisfy the constraint 'Object3DEventMap'.
```
Remove the unnecessary specified generic.

fix: remove problematic Object3D generic

---

src/core/PointerLockControls.tsx

```<PointerLockControls>``` were adding events on unmount instead of removing them. I noticed it since I was using a state to conditionally render the component, and the _listeners prop was showing more items being added to the array 
Changed the addEventListeners on unmount to removeEventListeners in the PointerLockControls.tsx component.

fix(PointerLockControls): Changed addEventListener to removeEventListener on unmount

---

README.md
src/core/Segments.tsx

The `Segments` component currently passes on any unrecognized props to its `LineMaterial`, but the type definition for `SegmentsProps` does not allow any such parameters to be supplied.
https://github.com/pmndrs/drei/blob/1169c02fcfd1151fa08effb4ca7215f91b140f53/src/core/Segments.tsx#L8-L12
https://github.com/pmndrs/drei/blob/1169c02fcfd1151fa08effb4ca7215f91b140f53/src/core/Segments.tsx#L81-L88
The `{...rest}` spreading was presumably added for a reason, but it is currently impossible to take advantage of. I ran into this issue when attempting to create dashed segments.
This pull request modifies the type definition of `SegmentsProps` to allow `LineMaterialParameters` to be passed through to the underlying line material, which I believe was the original intent.
I updated README.md …

fix: add material parameters to `SegmentsProps`

---

package.json
src/core/FaceLandmarker.tsx
yarn.lock

Using `moduleResolution: "bundler"` with `@react-three/drei` fails because `@mediapipe/tasks-vision@0.10.2` does not have any recognizable types when using `moduleResolution: "bundler"`:
This is (somewhat) fixed with later versions of `@mediapipe/tasks-vision`:
Update `@mediapip/tasks-vision`.

fix(types): update @mediapipe/tasks-vision

---

src/core/useBVH.tsx

This is a simple change that makes it `Bvh` only computes once on mount instead of recomputing every time there is a rerender in the tree.
Reactive recomputing is impractical in real time scenarios. Instead, I think we should encourage users to wrap `Bvh` arouund reusable graphs in components.

[fix] `Bvh` doesn't recompute every rerender

---

README.md

The Decal section in the documentation use polygonOffset on the Decal instead of the material, which has no effect.
Moved the polygonOffset and polygonOffset factor props to the child material.

docs(Decal): Moving polygonOffset to the Material

---

README.md
src/core/useBVH.tsx

My use case requires that the triangles of my mesh be in their original order. Garrett's library saw this use case and has created an experimental accomodation for it but that isn't currently carried through to the `<Bvh>` component. I know it's marked as experimental but I've been using it for some time now and I've had no issues. I think as long as Drei doesn't obscure it's experimental nature it's fine to include?
Includes the `indirect` option from [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh). I've copied his explanation of the option into the docs verbatim.

fix: include indirect BVH option

---

src/web/Html.tsx

Fixes #428, mirrors https://github.com/mrdoob/three.js/pull/27017.

fix(Html): use transform for perspective browser issues

---

src/web/CycleRaycast.tsx

CycleRaycast keyCode is not working because `event.keyCode` is always true. 
Fixed by adding parentheses on the condition

fix(CycleRaycast): raycast keycode

---

src/core/Text.tsx

Fixes #1725 with a workaround for a downstream Next.js compiler regression https://github.com/vercel/next.js/issues/58557.

fix(Text): lazy import Troika for Next issue

---

src/core/useGLTF.tsx

Inference for `useLoader` and `GLTFLoader` was properly fixed in https://github.com/pmndrs/react-three-fiber/pull/3105 upstream.
Adds an explicit return type to both regenerate types and harden this area.

fix(useGLTF): mirror inferred ObjectMap types

---

src/core/Stage.tsx

There was no typed way to skip the environment on a `Stage`.  To make it work, we needed to use `null as any` as a prop.
We support passing a null value to the environment value in `StageProps`
Resolves https://github.com/pmndrs/drei/issues/766

fix: Allow null environment in StageProps

---

package.json
src/core/StatsGl.tsx
yarn.lock

[Stats-GL](https://github.com/RenaudRohlinger/stats-gl) now supports postprocessing OOTB. Update the component with the new API.

feat: use stats-gl v2

---

src/core/Bounds.tsx

The last Bounds update was [breaking](https://github.com/pmndrs/drei/pull/1638#issuecomment-1850903843) for fit function.
Also, I've found an issue with controls-bounds-viewcube interaction.
Added reset() call to the fit function for non-orthographic camera case.
Also added camera.up update when animating

fix: Call reset from fit if the camera is non-orthographic

---

README.md

object on `<MotionPathControls>` is a ref:
`object?: React.MutableRefObject<THREE.Object3D>`
current example can't reach the lookAt function and throws error.

docs(MotionPathControls): useMotion example

---

src/core/AccumulativeShadows.tsx

When component is unmounted it throws.
The way its currently written
```js
React.useLayoutEffect(() => {
const group = gLights.current
if (parent) parent.lights.set(group.uuid, api)
return () => void parent.lights.delete(group.uuid)
}, [parent, api])
```
The check for valid parent is done for the lights.set, but there is no check on the
```js
return () => void parent.lights.delete(group.uuid)
```
so if parent is null this ^ line throws
prevents AccumulatedShadows from throwing when parent is null

AccumulatedShadows NPE protection

---

src/web/ScrollControls.tsx

- There is a typo in the ScrollControls storybook documentation
- Fixed the typo, and the default value (see screenshots in QA section below)
- Horontal -> Horizontal
- Default damping descriptions says 0.2s when it is actually 0.25s
1. Run `yarn storybook`
2. Go to Storybook -> ScrollControls, see documentation
Before:
After:

docs(ScrollControls): fix typo and default value description for damping

---

src/core/Outlines.tsx

Currently some Outlines props are marked as required even though they have default values. This results in the LSP complaining when these props are not set by the user. Since these values have a default value we shouldn't make them required.
This change marks all props optional so that users don't have to declare them if they want to use the default values.

fix(Outlines): Mark all Outlines props as optional

---

src/core/MeshDistortMaterial.tsx
src/core/MeshWobbleMaterial.tsx
src/core/useBoxProjectedEnv.tsx

The types have errors when used with @types/three@0.160.0, because [the `Shader` type was removed in @types/three@0.160.0](https://github.com/three-types/three-ts-types/releases/tag/r160) due it it being used in ways it wasn't intended to be used. The type errors are:
```
Error: ./node_modules/@react-three/drei/core/MeshDistortMaterial.d.ts(1,64): error TS2305: Module '"three"' has no exported member 'Shader'.
Error: ./node_modules/@react-three/drei/core/MeshWobbleMaterial.d.ts(1,64): error TS2305: Module '"three"' has no exported member 'Shader'.
Error: ./node_modules/@react-three/drei/core/useBoxProjectedEnv.d.ts(6,37): error TS2694: Namespace '"/home/runner/.yarn/berry/cache/@types-three-npm-0.160.0-e7f9e2774b-10c0.zip/node_modules/@types/three/build/three.module"' has no exported …
```

fix(types): remove references to Shader type

---

src/core/Text.tsx

Reverts pmndrs/drei#1726 as it's no longer needed and proved ineffective for a downstream issue in Next.js.

Revert "fix(Text): lazy import Troika for Next issue"

---

src/web/ScrollControls.tsx

Currently, when using the `Scroll` component with the html prop, the style prop is missing in the prop list. So to fix the missing auto-complete, I made the change in question.
Updated the `ScrollProps` type to better fit the current needs. The `style` prop will be optional when the `html` is passed and it will not be accepted without the `html` prop.
without passing `html` prop:
with html prop:

fix: missing style prop from type in ScrollControls

---

src/core/Line.tsx

The `Line` component doesn't currently allow Vector4's which are common with Nurb Lines (see #1781)
Added `Vector4` to the import and Point Array handling

fix: added Vector4 to Line component points input

---

README.md
package.json
src/core/Instances.tsx
src/web/ScrollControls.tsx
src/web/View.tsx
yarn.lock

- no refs
- no double definitions in and out the canvas
- no index counting
- canvas straight inside the dom, where you want it to appear
- fully dynamic, views can pop in and out any time in any number
- doesn't render views that are offscreen or invisible
- fully backwards compatible to the old api
Demo: [inline views
](https://codesandbox.io/s/view-tracking-forked-f5wnde?file=/src/App.js)
Views use gl.scissor to cut the viewport into segments. You tie a view to a tracking div which then controls the position and bounds of the viewport. This allows you to have multiple views with a single, performant canvas. These views will follow their tracking elements, scroll along, resize, etc.
It is advisable to re-connect the event system to a parent that contains both the canvas and the html …

feat: inline views

---

src/core/RenderTexture.tsx

Resolves #1789
Save and restore value of `gl.xr.enabled` before/after the RenderTexture render, set to `false` during.
I used an untyped `let` variable to follow the pattern used for `oldAutoClear`, though it may be safer to give these a `boolean` type annotation or just use `const` inside the frame loop.

fix(RenderTexture): disable XR during RenderTexture render

---

README.md

~~SpotLightShadows~~ -> SpotLightShadow
update section with correct export name.
https://github.com/pmndrs/drei/blob/ffb815d9ffb6d7aaf6db0cb6224445f7e29e26a5/src/core/SpotLight.tsx#L275C17-L275C32
[ x ] Documentation updated

docs(SpotLightShadow): correct spelling

---

README.md
src/core/MeshTransmissionMaterial.tsx

I changed `distortionScale` and `temporalDistortion` to be optional on the `MeshTransmissionMaterialType` because they have defaults as mentioned in the docs comments.

fix: optional types for MeshTransmissionMaterialType

---

src/core/CameraControls.tsx

CameraControls components do not need to have EventDispatcher methods as props.
I omitted the props related to EventDispatcher from CameraControlsProps.

fix: omit unnecessary types from CameraControlsProps

---

src/core/Line.tsx

Closes #1813 
In the `Line2` `LineMaterial` the `color` has to be set to white to allow the `vertexColors` to work correctly. 
Not setting it, or setting it to anything but white causes it to ignore both the `color` value and the `vertexColors`
Now, I could have just said "You have to pass white" but I instead changed the default value to white, and also added an overwrite so if you pass `vertexColors` it automatically forces the `color` to white (`0xffffff`).
I'm not sure if there was a reason to set it to black...
I have updated [the CSB from the original ticket. ](https://codesandbox.io/p/sandbox/line-error-report-v3vrmj?file=%2Fsrc%2FApp.jsx%3A46%2C22)
You can see passing no color, or passing a green color causes the line to draw as black.
Passing white causes it to render correctly …

fix: change default to white and add overwrite when using vertex colors

---

src/core/ScreenSizer.tsx
tsconfig.json

The broken import causes a type error in the TS declaration files.
Fixed the import path and removed the `baseUrl` setting from the TSConfig to prevent it in the future.

fix(ScreenSizer): use relative import

---

.storybook/stories/DragControls.stories.tsx
README.md
src/web/DragControls.tsx
src/web/index.ts

Resolves #197.
This PR introduces a custom DragControls component that closely mimics the implementation of PivotControls. Instead of directly inheriting from the built-in three.js DragControls class, this implementation wraps the child object in a Group and manages gesture controls with pmndrs/use-gesture. This approach offers flexibility for axis locking, drag limits, and custom drag events (start, drag, end).

feat: add DragControls component

---

src/core/ScreenSizer.tsx

`ScreenSizer` `scale` should be optional, so if not set it defaults to `1`.
On my last PR, I missed that `scale` wasn't set as optional, so it forces the user to set the scale. Instead it should be optional, and default to `1` when not set.
Set `ScreenSizer` `scale` prop as optional.

fix: ScreenSizer scale should be optional

---

package.json
src/core/Detailed.tsx
src/core/Effects.tsx
src/core/Float.tsx
src/core/Grid.tsx
src/core/Instances.tsx
src/core/Lightformer.tsx
src/core/MarchingCubes.tsx
src/core/MeshReflectorMaterial.tsx
src/core/OrthographicCamera.tsx
src/core/PerspectiveCamera.tsx
src/core/Points.tsx
src/core/PositionalAudio.tsx
src/core/QuadraticBezierLine.tsx
src/core/Reflector.tsx
src/core/ScreenSizer.tsx
src/core/ScreenSpace.tsx
src/core/Segments.tsx
src/core/SpotLight.tsx
src/web/ScrollControls.tsx
yarn.lock

Continues #1009 since `react-merge-refs` has compatibility and correctness issues.

fix: react-merge-refs => useImperativeHandle

---

src/core/Center.tsx
src/core/Environment.tsx
src/core/MeshDiscardMaterial.tsx
src/core/Trail.tsx
src/core/useIntersect.tsx
src/core/useMatcapTexture.tsx

The ambient THREE namespace was [removed in `@types/three@0.162.0`](https://github.com/three-types/three-ts-types/releases/tag/r162).
Removes usages of the ambient THREE namespace.

fix(types): fix usages of ambient THREE namespace

---

src/core/Environment.tsx
src/core/useEnvironment.tsx

[`TextureEncoding` was removed in r162](https://github.com/three-types/three-ts-types/releases/tag/r162).
Replace the `TextureEncoding` type with an inline type to avoid a breaking change.

fix(types): replace TextureEncoding with inline type

---

README.md

as is
`(title)[link]`
to be
`[title](link)`

docs: fix grammar at Text3d typeface link

---

README.md
src/core/Cloud.tsx

Updated cloud docs
- Missing "frustumCulled" in the readme file
- In `Cloud.tsx` the frustum culled option was written under `CloudProp` instead of `CloudsProp`
- Added frustumCulled in the readme file
-  Moved "frustumCulled" from  `CloudProp`  into `CloudsProp` 
- Code is correct, `frustumCulled=true` is applied on instancedMesh  in < Clouds > , so this is just a doc update

docs: update Clouds "frustum culled" info

---

src/core/Effects.tsx
src/core/useEnvironment.tsx
src/helpers/deprecated.ts

[`TextureEncoding` was removed in r162](https://github.com/three-types/three-ts-types/releases/tag/r162). This was fixed in https://github.com/pmndrs/drei/pull/1858, but another reference to TextureEncoding snuck in through https://github.com/pmndrs/drei/pull/1850.
Created a shared `TextureEncoding` type instead of importing from `three`.

fix(types): remove reference to THREE.TextureEncoding

---

src/core/SpriteAnimator.tsx

(👋 first time contributor here, just wanted to say thank you for all your work)
Using SpriteAnimator (most noticeable with large) spritesheets sometimes results in sprite shaking. Looked at why that happens (at first was thinking sprite texture filtering...etc) it seems the `framesH` and `framesV` calculations have small precision issues which result in visual shake in the sprite as it's playing (since it's use to calculate the texture offsets).  Simply rounding them solves the visual shake .
Here is a small Codesandbox reproduction of the issue ([Sandbox](https://codesandbox.io/p/sandbox/drei-spritesheet-shake-reproduction-mvx45v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType …

fix: round up framesH and framesV calc to solve visual shake in SpriteAnimator

---

src/web/Loader.tsx

Just a small suggestion. 💙
Updated the type definition to CSSProperties for style-related props in the Loader component. Previously, it was for style objects.
The `any` type was used, but type safety was not guaranteed. By using CSSProperties
Style-related properties receive explicit type checking, reducing developer mistakes.
containerStyles, innerStyles, barStyles, and dataStyles, which were previously applied as `any` type, have been updated to CSSProperties.

fix: update loader style type definitions to CSSProperties

---

README.md
src/web/Html.tsx

onOcclude from the Html component description imply that we receive that visible state of the Html, while it sends the opposite aka hidden / isHidden 
I chose hidden because it match the existing example from the doc.
```jsx
const [hidden, set] = useState()
<Html
occlude
onOcclude={set}
style={{
transition: 'all 0.5s',
opacity: hidden ? 0 : 1,
transform: `scale(${hidden ? 0.5 : 1})`
}}
/>
```
Changed `visible` to `hidden`

fix onOcclude description

---

src/web/Select.tsx

I noticed that removal of event listener was not properly done, potentially causing unnecessary computations after e.g. canvas resize.
Added the capture option set to `true` to `removeEventListener` for 'pointermove' to match the corresponding `addEventListener`.
Reference to documentation:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#matching_event_listeners_for_removal

fix: actually removing event listener by setting capture option to true

---

README.md
src/core/Grid.tsx

Updates the Grid and GridMaterial to take an optional parameter to move the fade to happen around the origin rather than the camera.
I have a need for the grid to fade around the origin, putting the main object on an "island" of grid. 
It's a simple change that adds an optional number parameter that can alter the fade origin from the camera to the world origin.

Added Fade From to Grid.tsx

---

src/web/ScrollControls.tsx

There was no problem with the type of the previous Scroll Props, but when I analyzed the type, it was a bit difficult to understand. Or, I think it is poor in maintainability and readability.
It was divided into two types of interface and later modified to improve maintainability and readability.

fix: refactor the ScrollProps type for maintainability and readability

---

src/web/View.tsx

The return type of `View.Port` was `ReactNode` which is not correct as it's supposed to be used as a JSX element. The documented usage of the component/function was giving the following error:
The main reason why `ReactNode` cannot be used like this is because `ReactNode` type can possibly be `undefined` which is not valid JSX (`null` is the valid alternate). See more on stackoverflow: https://stackoverflow.com/questions/72392225/reactnode-is-not-a-valid-jsx-element
The return type of `View.Port` is changed to `JSX.Element` so it can be used as JSX. The TypeScript error is gone now.

fix: use correct return type for View.Port

---

src/core/useTrailTexture.tsx

Types were added to parts where types were not applied.
TrailTexture.js does not exist in the link, so the comment has been deleted.
- The URL link in the comment was deleted because it was a URL link that did not exist. 
- Added a part where the type is not applied.
- Since ctx may not exist, we added throw Error to be called when it is a null value.

fix: add types to useTrailTexture and remove comments

---

src/core/useTexture.tsx

Since there is a nested ternary operator and an `any` type, we refactored the nested ternary operator to make it easier to understand and maintain, and modified the `any` type.
- Things that were of type any were changed to type unknown.
- We refactored the ternary operator type nested in the MappedTextureType type to make it easier to understand and maintain.
- Simplify texture processing logic in useEffect to handle various input types more uniformly.
- Because the string type is not a subtype of any[], it always returns string. So I removed the extends any[] type and modified the code to make it easier to understand.

fix: modify nested ternary operators and any type in useTexture

---

src/core/useVideoTexture.tsx

Fixes #1917 by initializing hls.js only when in a browser environment and when supported.

fix(useVideoTexture): lazy initialize hls.js when supported

---

src/core/GradientTexture.tsx

A small tweak. `GradientTexture` currently only supports `string` colors, meaning you cannot use other Three.js color representations like `number` or `THREE.Color`. 
```tsx
<GradientTexture colors={['#7cbfff', '#fff']} stops={[0, 1]} />
```
Add support for any valid color representation.
```tsx
<GradientTexture colors={[0x7cbfff, '#fff']} stops={[0, 1]} />
```
```tsx
<GradientTexture colors={[new THREE.Color().setHSL(0.6, 1, 0.6), '#fff']} stops={[0, 1]} />
```

feat(GradientTexture): Support any color representation

---

src/core/Stats.tsx
src/core/StatsGl.tsx

Both `Stats` and `StatsGl` don't remove class names set via the `className` prop on rerender. In the following example, if `showStats` is initially `false` and then later changes to `true`, the `Hidden` class does not get removed from the DOM element.
```tsx
<Stats className={`Stats ${showStats ? '' : 'Hidden'}`} />
```
Fixed by removing the previously added class names during `useEffect` cleanup.

fix: Stats and StatsGl don't remove previous class names on rerender

---

README.md

Storybook links for Lines (and beziers) and MapControls seem to be outdated.
this change is prob way too trivial for a checklist

chore: fix stale links in README.md

---

src/core/Edges.tsx

fixes #1893
A previous refactor of the `<Edges>` component made it so that passing `geometry` as a prop no longer worked. This is a breaking change for many users that prevented upgrading.
This PR restores the expected behavior from the README:
> It pulls the geometry automatically from its parent, optionally you can ungroup it and give it a geometry prop.
> https://github.com/pmndrs/drei?tab=readme-ov-file#edges

fix: restore Edge component to accept geometry as prop

---

src/core/RenderTexture.tsx

RenderTexture currently does not work with WebXR
disable `renderer.xr.isPresenting` while rendering to the framebuffer and reset to the previous render target when done

fix: RenderTexture for WebXR

---

custom.d.ts
src/core/Bvh.tsx
src/core/MeshRefractionMaterial.tsx
src/core/shaderMaterial.tsx
src/materials/MeshRefractionMaterial.tsx
tsconfig.json

Fixes https://github.com/pmndrs/drei/issues/2013
Removes `custom.d.ts` that stubs `three-mesh-bvh` types and fix resulting type errors

fix(types): reference to three-mesh-bvh

---

src/materials/MeshRefractionMaterial.tsx

Refactors `MeshRefractionMaterial` to use three's color chunks so instance colors work again.

fix(MeshRefractionMaterial): use color chunks, support opacity prop

---

README.md
src/core/Float.tsx

Fixes #2033 
The `Float` component does not work when the Canvas frameloop is set to `demand`.
I added the `autoInvalidate` prop that can be set to `true` when using on-demand rendering. 
This will ensure that `invalidate` is called while `Float` is enabled. 
After a discussion in the community Discord, it was decided that calling `invalidate` should be opt-in to ensure the developer controls the frameloop. 
The default is `false` to prevent this from being a breaking change.

feat(Float): add autoInvalidate prop for on-demand rendering

---

src/core/Outlines.tsx

Fixes #2043, where expo-gl will not accept coerced values for uniforms.

fix(Outlines): use correct uniform type

---

src/core/Svg.tsx

`<Svg>` component is broken after `three@>=0.152`.
Added `renderOrder` following https://github.com/mrdoob/three.js/pull/26114 .
To test this, you need to have three@>=0.152. `Drei` storybook uses `three@0.151.0` so you won't see the bug on the official storybook.
This is the same as https://github.com/pmndrs/drei/pull/1938 but without having to remove `transparent`, as that isn't required in the `three.js` examples either.

Fix: renderOrder of <Svg> meshes

---

src/core/Billboard.tsx

Fixes #2042
With https://github.com/mrdoob/three.js/pull/28533, matrix flags now have an effect, but Billboard relied on them being ignored.

fix(Billboard): don't disable matrix update

---

src/core/GizmoHelper.tsx

When using camera-controls sets target via the getTarget method, and updates the control position via the setPosition method.
Allows GizmoHelper to be used alongside CameraControls/camera-controls.
resolves #1399 
Fixes two issues:
1. `CameraControls` doesn't expose a `target` property directly - so when `focusPoint` is set at animation start, get the target via `CameraControls` `getTarget` instead.
2. `CameraControls` doesn't seem to like having its camera moved directly, and will continuously attempt to reset the `mainCamera`'s position - the fix is to call `CameraControls` `setPosition` method after the `mainCamera`'s position is updated, and before it has a chance to revert it.
I did create a storybook entry that's just a duplicate of the GizmoHelper story below but using …

fix(GizmoHelper): allow GizmoHelper to be used with camera-controls

---

src/core/GizmoHelper.tsx

Fixes: 
- https://github.com/pmndrs/drei/issues/2074 
Setting the `dummy.up` vector was unnecessary.

fix: #2074 GizmoHelper with Z UP camera

---

.storybook/stories/Instances.stories.tsx
docs/performances/instances.mdx
src/core/Instances.tsx

When creating custom instances, it's had to keep track of the types of the instance attributes. This PR adds a generic to createInstance so that instances can be easily typed.
```tsx
interface SphereAttributes {
myCustomAttribute: number
}
const [SphereInstances, Sphere] = createInstances<SphereAttributes>()
<Sphere
position={[4, 5, 6]}
myCustomAttribute={1} // typed
/>
```
- Added a generic to createInstances
- Updated readme
- Added storybook examples for instances
❤️

turn createInstances into a generic function

---

README.md
docs/staging/use-environment.mdx

The docs were moved recently from the READ.ME to separate doc files. The `useEnvironment` docs got misplaced. 
I moved the docs from the READ.ME to the correct docs page

fix: misplaced useEnvironment docs

---

package.json
src/materials/MeshRefractionMaterial.tsx
yarn.lock

There are currently type errors when using drei with `three-mesh-bvh@^0.7.7`, since they added the `shaderIntersectFunction` type definition in https://github.com/gkjohnson/three-mesh-bvh/pull/697:
```
./node_modules/@react-three/drei/materials/MeshRefractionMaterial.d.ts(3,11): error TS2451: Cannot redeclare block-scoped variable 'shaderIntersectFunction'.
./node_modules/three-mesh-bvh/src/index.d.ts(318,14): error TS2451: Cannot redeclare block-scoped variable 'shaderIntersectFunction'.
```
Update `three-mesh-bvh` and remove module augmentation

fix(types): shaderIntersectFunction is defined by three-mesh-bvh

---

src/core/GradientTexture.tsx

Closes issue #1962, where the `type` property of `Texture` was conflicting with the `type` property of `GradientTexture`.
Use `Omit` to remove `Texture`'s `type` property from the interface and removed a now-unnecessary `@ts-ignore`.

fix: GradientTexture type overlapping with Texture type

---

src/core/useSpriteLoader.tsx

These changes aim to make the useSpriteLoader function more robust and provide better error feedback to developers.
This commit refactors the useSpriteLoader function to improve error handling when loading standalone sprites. Previously, if neither the textureUrl nor the input was provided, the function would silently fail. Now, it throws an error indicating that either the textureUrl or the input must be provided. Additionally, if an invalid texture URL is provided, it throws an error indicating that a valid texture URL must be provided. The error handling has been enhanced to provide more informative error messages.

refactor: Improve error handling in useSpriteLoader

---

docs/loaders/use-sprite-loader.mdx
docs/misc/sprite-animator.mdx
src/core/SpriteAnimator.tsx
src/core/useSpriteLoader.tsx

Added the canvasRenderingContext2DSettings prop to the SpriteAnimator component in the core module
resolves #2103 
add ability to enable `willReadFrequently` as recommended by https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

feat: add prop to configure canvasRenderingContext2DSettings

---

src/core/SpriteAnimator.tsx

the types were technically lying
simply correct the type
we can either keep it as nullable or provide a default value that is of type SpriteAnimatorState
example of default value:
```ts
const context = React.createContext<SpriteAnimatorState>({
current: undefined,
offset: undefined,
hasEnded: undefined,
ref: undefined,
})
```

refactor: Correct SpriteAnimator context type

---

vite.config.js
vite.config.ts

the extra file seemed redundant
consolidate into one config file

refactor: use vite.config.ts as the sole config file

---

docs/controls/face-controls.mdx
src/web/FaceControls.tsx

feat(facecontrols): adding a return value for detect()

---

.github/dependabot.yml
.github/workflows/stale.yml
.husky/pre-commit
.husky/pre-push
.prettierignore
.storybook/stories/Line.stories.tsx
package.json
src/core/Cloud.tsx
src/core/GizmoHelper.tsx
src/core/Grid.tsx
src/core/Line.tsx
src/core/StatsGl.tsx
src/core/useEnvironment.tsx
src/web/KeyboardControls.tsx
src/web/pivotControls/PlaneSlider.tsx

formatting was not checked by CI: mal-formatted files have leaked into the code
fix and harden this, so it could not happen anymore

harden on formatting

---

.storybook/stories/FaceControls.stories.tsx
docs/controls/face-controls.mdx
docs/misc/face-landmarker.mdx
src/web/FaceControls.tsx
src/web/FaceLandmarker.tsx

Optionally, we can now pass `faceLandmarkerResult` from the outside, allowing us to fully control the face detection from the video-texture:
```tsx
// faceLandmarker
const videoTextureRef = useRef(null)
const [faceLandmarkerResult, setFaceLandmarkerResult] = useState()
<WebcamVideoTexture
ref={videoTextureRef}
onVideoFrame={(now) => {
const videoTexture = videoTextureRef.current
if (!faceLandmarker || !videoTexture) return
const videoFrame = videoTexture.source.data
const result = faceLandmarker.detectForVideo(videoFrame, now) // DETECTION HERE
setFaceLandmarkerResult(result)
}}
/>
<FaceControls manualDetect faceLandmarkerResult={faceLandmarkerResult} />
```
otherwise, a video-texture is automatically instanciated for us, like before

`FaceControls` simplified

---

src/core/Image.tsx

Image gets skewed, when updating the `scale` field.
Consider this [codepen](https://codesandbox.io/p/sandbox/clever-night-cxwhm3).
At first, you can see that all borders are visible. When you click on the image, it gets bigger, but it becomes skewed (the borders are no longer visible). Even resetting the `scale` back to `1` (by clicking) doesn't fix the skew.  
Turns out, that the `useLayoutEffect` is missing dependencies in the dependency array.  
After adding them, the issue is fixed, and the change of scale works properly.

fix: Properly scale the image when the scale prop is changed

---

package.json
yarn.lock

Fixes #2253
`"@react-three/fiber": "9.0.0-rc.1"` does not satisfy the `^8` peer dependency declared in Drei.
According to [semver](https://www.npmjs.com/package/semver), `^9.0.0-0` allows pre-releases.
It also allows regular `^9` versions such as `9.2.1`, but not other pre-releases, such as `9.2.1-rc.0`.

chore(deps): add ^9.0.0-0 to R3F peer dependency

---

src/core/ArcballControls.tsx
src/core/DeviceOrientationControls.tsx
src/core/FlyControls.tsx
src/core/Image.tsx
src/core/MapControls.tsx
src/core/OrbitControls.tsx
src/core/PointerLockControls.tsx
src/core/Sparkles.tsx
src/core/StatsGl.tsx
src/core/TrackballControls.tsx
src/web/FaceControls.tsx
src/web/ScreenVideoTexture.tsx
src/web/WebcamVideoTexture.tsx

Fixes miscellaneous type issues from updates to upstream types.

fix: misc type issues

---

src/core/Environment.tsx

Fixes a memory leak in `Environment` where intermediate textures are not disposed on unmount.

fix(Environment): dispose on unmount

---

package.json
yarn.lock

Reverts #2259 which was in error. React 19 support is tracked in #2284.

fix: exclude R3F v9 from peer deps

---

src/core/Outlines.tsx

Previously, using `<Outlines/>` on a mesh which has morph targets would throw an error.
This is fixed by copying the morph targets to the created geometry, and keeping them in sync by updating them when re-rendered.

fix: Outlines on meshes with morphTargets

---

src/core/GizmoHelper.tsx

Fixes:
- #2321 
Set dummy.up to mainCamera.up (otherwise dummy.up is always Y up)

fix: GizmoHelper rotations with Z up camera

---

src/core/Billboard.tsx

Somewhere along the way with Billboard, a wrapping Group was added, but some refs used to enforce axis lock were not updated to point to the inner group, which is the one being oriented.
Updated axis lock logic to utilize the inner group's ref

fix: Apply billboard axis lock to right group

---

src/core/Cloud.tsx
src/core/Float.tsx
src/core/MeshDistortMaterial.tsx
src/core/MeshTransmissionMaterial.tsx
src/core/MeshWobbleMaterial.tsx
src/core/Stars.tsx

A very simple PR
Just used the Cloud component and I noticed it messed up 'the time'
I then saw that many components call `clock.gelapsedTime()` on the main clock instead of reading the `.elapsedTime` property
Calling `getElapsedTime()` update the delta of the clock and then returns `.elapsedTime`
Clock source in three.js
https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js
Edit: In case you want the elapsed time precisely at the moment of the method call, use a separate clock for that.
I'd add that in 99% of case, you want the same elapsed time for all object in the current frame, making reading `.elapsedTime`  even better than `clock.gelapsedTime()` to fully sync everything.
This could be added to the gotcha section of the doc because I come across this issue in most …

fix: do not use getElapsedTime on the main state clock, it messes up the delta

---

docs/misc/detect-gpu-use-detect-gpu.mdx

docs: fix typo to compare GPUTier to 0 instead of "0"

---

docs/controls/motion-path-controls.mdx
src/core/MotionPathControls.tsx

Adding control of the motion state of MotionPathControls via the reference.
Adding `debugColor` property to change debug helpers color.
Adding `loop` property to control if the target object loop back to the start when reaching the end of the curve.
Avoid using only the `useMotion` hook inside MotionPathControls component to control the target object.
Add `motion` property to the MotionPathControls ref.
Handle `useMotion` hook error when used outside of MotionPathControls component.
Update doc.

feat: add MotionPathControls control via ref + add two properties

---

src/core/CatmullRomLine.tsx

The `segments` property in `CatmullRomLineProps` was conflicting with `LineProps`. Since `LineProps` already declares `segments`, redeclaring it in `CatmullRomLineProps` caused TypeScript errors.
This PR resolves the issue by omitting `segments` from `LineProps` in `CatmullRomLineProps`, allowing users to define `segments` without type conflicts.
- Added `'segments'` to `Omit<LineProps, 'ref' | 'segments'>` to prevent redeclaration issues.
- Ensured compatibility with existing props.
- TypeScript errors related to `segments` no longer appear.
**Additional Comments**  
- This PR **resolves** [#1476](https://github.com/pmndrs/drei/issues/1476).

fix: resolve CatmullRomLineProps conflict with LineProps 'segments'

---

.storybook/stories/Merged.stories.tsx
src/core/Instances.tsx

`Merged` stopped working with #2318, which made it non-recursive. This was a partial fix that needs more work. For now, I've added rolled back but added slightly loose type safety for children.
A proper fix will be completely type-safe and allow either `children` signature, regardless of the input props. This is not possible with the current recursive implementation.

fix(Merged): restores recursive implementation

---

src/core/shaderMaterial.tsx

Infers the returned parameters and uniforms, whereas this was not typesafe before.
```tsx
import { shaderMaterial } from '@react-three/drei'
const CustomMaterial = shaderMaterial({ time: 0 }, vertexShader, fragmentShader)
const material = new CustomMaterial()
material.onBeforeRender = () => material.time++
```
Additionally, the returned class can be used for type-safe extending as JSX.
```tsx
import { extend, ThreeElement } from '@react-three/fiber'
import { shaderMaterial } from '@react-three/drei'
const CustomMaterial = shaderMaterial({ time: 0 }, vertexShader, fragmentShader)
declare module '@react-three/fiber' {
interface ThreeElements {
customMaterial: ThreeElement<typeof CustomMaterial>
}
}
extend({ CustomMaterial })
// alternatively,
// const Component = extend(CustomMaterial) …
```

fix(shaderMaterial): infer uniforms types

---

src/core/shaderMaterial.tsx

Hi, thanks for the amazing library!
https://github.com/pmndrs/drei/pull/2375 improves type safety for `shaderMaterial`, but it also seems to have broken some basic shaders.
For example, if we create two grids (one red, one blue):
```tsx
import { Canvas } from "@react-three/fiber";
import { Grid } from "@react-three/drei";
function App() {
return (
<>
<Canvas>
<Grid
cellColor="#ff0000"  // Red
sectionColor="#ff0000"  // Red
cellThickness={2}
position={[0, 0, 0]}
/>
<Grid
cellColor="#0000ff"  // Blue
sectionColor="#0000ff"  // Blue
cellThickness={2}
position={[0, 0, 1]}
/>
</Canvas>
</>
);
}
export default App;
```
We currently get two blue grids:
The culprit appears to be a clone that was removed.
This PR adds the clone back, which gives us the correctly colored grids:
My dependency …

fix(shaderMaterial): clone uniforms in `shaderMaterial` constructor

---

src/core/MeshReflectorMaterial.tsx

The `<MeshReflectorMaterial/>` had a useMemo referencing a blur array which would be a different object reference every React render, causing the FBO and other expensive things to be recreated every render.
Changed the useMemo to check the values of the blur array rather than the array itself.

fix: MeshReflectorMaterial creating FBO every re-render

---

src/core/CameraControls.tsx

useful to access `CameraControls.ACTION` static class prop:
```tsx
import { CameraControlsImpl } from "@react-three/drei";
const { ACTION } = CameraControlsImpl;
<CameraControls mouseButtons={{
left: ACTION.OFFSET,
// ...
}} />
```

chore: exporting CameraControlsImpl class

---

.storybook/stories/CameraControls.stories.tsx
docs/controls/camera-controls.mdx
src/core/CameraControls.tsx

supports all `onX` https://github.com/yomotsu/camera-controls/tree/dev?tab=readme-ov-file#events
| Event name          | Timing |
| ------------------- | ------ |
| `'controlstart'`    | When the user starts to control the camera via mouse / touches. ¹ |
| `'control'`         | When the user controls the camera (dragging). |
| `'controlend'`      | When the user ends to control the camera. ¹ |
| `'transitionstart'` | When any kind of transition starts, either user control or using a method with `enableTransition = true` |
| `'update'`          | When the camera position is updated. |
| `'wake'`            | When the camera starts moving. |
| `'rest'`            | When the camera movement is below `.restThreshold` ². |
| `'sleep'`           | When the camera end moving. |
+ backward compat …

feat: CameraControls support for 1:1 events `onX` callback props

---

src/core/Decal.tsx

The inbuilt helper is great for Decal but it only updates once on mount, if you update the transform props it will never update the helpers transforms until it remounts.
I've moved the transform update into the same effect as the decal so they stay in-sync. This makes it work much better with Triplex:
https://github.com/user-attachments/assets/3bfe3af6-f04e-4361-be4b-a6c1276ee286
---
This pull request is sponsored by [Triplex](https://triplex.dev) — your visual workspace for React / Three Fiber.

Update Decal helper transforms when transforms change

---

src/core/CameraControls.tsx

CameraControls's `enabled` property is for disabling "inputs" only: programmatic methods should sill work
We were previously using it to conditionally update() or not, hence disabling also programmatic calls instead of just "inputs" as expected by upstream lib -- this was a mistake
we revert this, and just do not change the upstream's lib behavior which in any case, already handle the necessity of `update()`ing with its internal `_needsUpdate`

fix(CameraControls): always run cc .update() regardless of .enabled

---

.storybook/stories/RoundedBox.stories.tsx
docs/shapes/rounded-box.mdx
src/core/Caustics.tsx
src/core/Image.tsx
src/core/RoundedBox.tsx

Per: https://discourse.threejs.org/t/is-it-possible-to-use-roundedbox-with-react-three-csg/57573
@react-three/csg requires geometry so a geometry export would be useful, Paul had recommended PR for that.
Created a RoundedBoxGeometry export. Minor fixes to RoundedBox.

feat: Create and export RoundedBoxGeometry

---

docs/abstractions/use-animations.mdx

Not sure how to build the docs for myself locally to see if it is fixed, but this is a small change and should fix the broken link.

docs: fix broken useAnimations source link

---

package.json
src/native/package.json

Fixes import resolution in the latest version of metro when `unstable_enablePackageExports` is enabled `(default: true)`.
Resolves #2493.
Adds a package.json to the root of the native sub-path with legacy import mappings. Metro will use the fallback/legacy import strategy when importing from `'@react-three/drei/native'`.
*Note: As this doesn't change any code and it resolves an issue in import resolution in metro, it may not require a new patch version. If you feel that we want to mark it as a patch instead, i can update the commit to `fix` instead. LMK.*

fix: adds native sub-path resolution for metro

---

.storybook/stories/Center.stories.tsx
docs/staging/center.mdx
src/core/Center.tsx

Allow passing an (inner) `object` for setting box3 from.

Center[object]

---

docs/gizmos/pivot-controls.mdx
src/web/pivotControls/AxisArrow.tsx
src/web/pivotControls/AxisRotator.tsx
src/web/pivotControls/ScalingSphere.tsx
src/web/pivotControls/context.ts
src/web/pivotControls/index.tsx

this PR closes ticket #2503
I need this urgently ;) would be nice if it can be merged soon

fix: add renderOrder to AxisRotator
